import { useMemo, useState } from "react";
import { Alert, Image, Pressable, Share, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { Badge, EmptyState, Panel, PrimaryButton, Screen, SecondaryButton, TopBar } from "../../components/ui";
import { mediaReferences } from "../../domain/analytics";
import type { MediaRef } from "../../domain/types";
import { captureMedia, chooseMedia, copyLocalMedia, deleteLocalMedia } from "../../storage/media";
import { useLogbook } from "../../state/logbook-context";
import { tokens } from "../../theme/tokens";

type Target = { id: string; kind: "trip" | "catch" | "gear"; label: string; collection?: "lures" | "flashers" | "rods" | "reels"; tripId?: string };
const next = <T,>(items: T[], current: T) => items[(items.indexOf(current) + 1) % items.length];

export function GalleryScreen(){
  const {logbook,update}=useLogbook();const router=useRouter();const [filter,setFilter]=useState("All"),[selectedId,setSelectedId]=useState(""),[targetId,setTargetId]=useState(""),[busy,setBusy]=useState(false);
  const close=()=>router.canGoBack()?router.back():router.replace("/(tabs)/more");
  const all=useMemo(()=>mediaReferences(logbook),[logbook]);const inbox=logbook.mediaInbox||[];const items=filter==="All"?all:all.filter(item=>item.owner===filter);
  const filters=["All",...Array.from(new Set(all.map(item=>item.owner)))];
  const targets=useMemo<Target[]>(()=>[
    ...logbook.trips.map(trip=>({id:`trip:${trip.id}`,kind:"trip" as const,label:`Trip · ${trip.date} · ${trip.title}`,tripId:trip.id})),
    ...logbook.trips.flatMap(trip=>trip.catches.map(fish=>({id:`catch:${trip.id}:${fish.id}`,kind:"catch" as const,label:`Catch · ${fish.species||"Fish"} · ${trip.date}`,tripId:trip.id}))),
    ...(["lures","flashers","rods","reels"] as const).flatMap(collection=>logbook[collection].map(item=>({id:`gear:${collection}:${item.id}`,kind:"gear" as const,label:`${collection.slice(0,-1)} · ${item.name||item.shortName||"Unnamed"}`,collection})))
  ],[logbook]);
  const selected=inbox.find(item=>item.id===selectedId);const target=targets.find(item=>item.id===(targetId||targets[0]?.id));
  const addToInbox=async(source:"camera"|"library")=>{setBusy(true);try{const media=await (source==="camera"?captureMedia("photo-queue"):chooseMedia("photo-queue"));if(media)await update({...logbook,mediaInbox:[...inbox,media]})}catch(error){Alert.alert("Media not added",error instanceof Error?error.message:String(error))}finally{setBusy(false)}};
  const assign=async()=>{if(!selected||!target)return;const category=target.kind==="gear"?target.collection:target.kind==="catch"?"catch-photos":"trip-photos";if(!category)return;const media=await copyLocalMedia(selected,category);let nextLogbook:any={...logbook,mediaInbox:inbox.filter(item=>item.id!==selected.id)};if(target.kind==="trip")nextLogbook.trips=logbook.trips.map(trip=>trip.id===target.tripId?{...trip,notePhotos:[...(trip.notePhotos||[]),media]}:trip);if(target.kind==="catch")nextLogbook.trips=logbook.trips.map(trip=>trip.id===target.tripId?{...trip,catches:trip.catches.map(fish=>target.id.endsWith(`:${fish.id}`)?{...fish,photos:[...(fish.photos||[]),media]}:fish)}:trip);if(target.kind==="gear"&&target.collection)nextLogbook[target.collection]=logbook[target.collection].map((item:any)=>target.id.endsWith(`:${item.id}`)?{...item,media:[...(item.media||[]),media]}:item);try{await update(nextLogbook)}catch(error){await deleteLocalMedia(media);throw error}await deleteLocalMedia(selected).catch(()=>{});setSelectedId("");setTargetId("")};
  const discard=(media:MediaRef)=>Alert.alert("Delete unassigned media?","This removes the local file and cannot be undone.",[{text:"Cancel",style:"cancel"},{text:"Delete",style:"destructive",onPress:async()=>{await deleteLocalMedia(media);await update({...logbook,mediaInbox:inbox.filter(item=>item.id!==media.id)});if(selectedId===media.id)setSelectedId("")}}]);
  return <Screen><TopBar title="Gallery" subtitle="Attached media and capture inbox" actions={<SecondaryButton label="Back" compact onPress={close}/>}/>
    <Panel title={`Capture inbox · ${inbox.length}`} subtitle="Collect now, assign later without interrupting a trip."><View style={s.actions}><PrimaryButton label="Take Photo / Video" compact loading={busy} onPress={()=>addToInbox("camera")}/><SecondaryButton label="Import from Library" compact disabled={busy} onPress={()=>addToInbox("library")}/></View>{inbox.length?<View style={s.inbox}>{inbox.map(item=><Pressable key={item.id} onPress={()=>{setSelectedId(item.id);setTargetId(targets[0]?.id||"")}} style={[s.inboxRow,item.id===selectedId&&s.inboxSelected]}><Thumb item={item}/><View style={s.grow}><Text style={s.title} numberOfLines={1}>{item.name||item.filename}</Text><Text style={s.date}>Unassigned · {item.mediaType}</Text></View><SecondaryButton label="Assign" compact onPress={()=>{setSelectedId(item.id);setTargetId(targets[0]?.id||"")}}/><SecondaryButton label="Delete" compact onPress={()=>discard(item)}/></Pressable>)}</View>:<Text style={s.help}>The inbox is empty. Media captured from a live trip can still attach directly to that trip.</Text>}</Panel>
    {selected?<Panel title="Assign media" subtitle={selected.name||selected.filename}>{targets.length?<><Pressable onPress={()=>{const ids=targets.map(item=>item.id);setTargetId(next(ids,target?.id||ids[0]))}} style={s.target}><Text style={s.targetLabel}>DESTINATION</Text><Text style={s.targetValue}>{target?.label} ›</Text></Pressable><View style={s.actions}><PrimaryButton label="Assign" onPress={assign}/><SecondaryButton label="Cancel" onPress={()=>setSelectedId("")}/></View></>:<EmptyState title="No assignment targets" description="Create a trip, catch, or gear item first."/>}</Panel>:null}
    <View style={s.filters}>{filters.map(item=><Pressable key={item} onPress={()=>setFilter(item)} style={[s.filter,item===filter&&s.active]}><Text style={[s.filterText,item===filter&&s.activeText]}>{item}</Text></Pressable>)}</View>
    {!items.length?<EmptyState title="No attached media found" description="Assign items from the capture inbox or attach media directly from trips, catches, and gear."/>:<View style={s.grid}>{items.map((entry,index)=>{const item=entry.media;const uri=String(item.uri||item.image||item.url||"");return <Pressable key={`${item.id}-${index}`} style={s.card} onPress={()=>uri&&Share.share({url:uri,message:String(item.caption||item.filename||"Fishing Logbook media")})}><Thumb item={item} large/><View style={s.copy}><Text style={s.title} numberOfLines={1}>{String(item.caption||item.filename||"Media")}</Text><View style={s.meta}><Badge tone="neutral">{entry.owner}</Badge>{item.captureTime?<Text style={s.date}>{String(item.captureTime).slice(0,16)}</Text>:null}</View></View></Pressable>})}</View>}
    <Panel title="Local media ownership"><Text style={s.help}>Originals remain in the app sandbox until you export or share them. Deleting an inbox item removes its unassigned local file; assigned media remains protected by its owner record.</Text></Panel>
  </Screen>
}
function Thumb({item,large=false}:{item:MediaRef;large?:boolean}){const uri=String(item.uri||item.image||item.url||"");return uri&&item.mediaType!=="video"?<Image source={{uri}} style={large?s.image:s.thumb}/>:<View style={large?s.video:s.thumbVideo}><Text style={s.videoText}>VIDEO</Text></View>}
const s=StyleSheet.create({actions:{flexDirection:"row",flexWrap:"wrap",gap:9},inbox:{borderTopWidth:1,borderTopColor:tokens.color.line},inboxRow:{minHeight:62,flexDirection:"row",alignItems:"center",gap:9,borderBottomWidth:1,borderBottomColor:tokens.color.line,paddingVertical:8},inboxSelected:{backgroundColor:tokens.color.activeBackground},thumb:{width:48,height:48,borderRadius:6,backgroundColor:tokens.color.black},thumbVideo:{width:48,height:48,borderRadius:6,alignItems:"center",justifyContent:"center",backgroundColor:tokens.color.black},grow:{flex:1},target:{padding:13,borderWidth:1,borderColor:tokens.color.line,borderRadius:8,backgroundColor:tokens.color.field,gap:5},targetLabel:{color:tokens.color.muted,fontSize:10,fontWeight:"900",letterSpacing:.6},targetValue:{color:tokens.color.text,fontWeight:"800"},filters:{flexDirection:"row",flexWrap:"wrap",gap:7},filter:{paddingVertical:7,paddingHorizontal:11,borderWidth:1,borderColor:tokens.color.line,borderRadius:999,backgroundColor:tokens.color.field},active:{backgroundColor:tokens.color.activeBackground,borderColor:tokens.color.chipLine},filterText:{color:tokens.color.muted,fontSize:12,fontWeight:"700"},activeText:{color:tokens.color.activeText},grid:{flexDirection:"row",flexWrap:"wrap",gap:12},card:{width:"47%",minWidth:150,flexGrow:1,maxWidth:310,borderWidth:1,borderColor:tokens.color.line,borderRadius:8,overflow:"hidden",backgroundColor:tokens.color.panel},image:{width:"100%",aspectRatio:1.25,backgroundColor:tokens.color.black},video:{width:"100%",aspectRatio:1.25,backgroundColor:tokens.color.black,alignItems:"center",justifyContent:"center"},videoText:{color:tokens.color.muted,fontSize:9,fontWeight:"900"},copy:{padding:10,gap:7},title:{color:tokens.color.text,fontWeight:"800"},meta:{flexDirection:"row",alignItems:"center",gap:7},date:{color:tokens.color.muted,fontSize:11},help:{color:tokens.color.muted,lineHeight:20}});
