from __future__ import annotations

import re
import subprocess
import sys
from copy import deepcopy
from pathlib import Path

from backend.backend_config import DEFAULT_LOGBOOK


ROOT = Path(__file__).resolve().parents[1]


def test_frontend_template_renders_all_partials_once(fish) -> None:
    payload = deepcopy(DEFAULT_LOGBOOK)
    payload["settings"]["theme"] = "dark"
    fish.logbook.write(payload, None)
    response = fish.client.get("/trips")

    assert response.status_code == 200
    markup = response.get_data(as_text=True)
    assert '<html lang="en" data-theme="dark">' in markup
    assert "Fishing Logbook" in markup
    assert 'id="tripListPanel"' in markup
    assert 'id="tripDialog"' in markup
    assert 'id="deleteTripButton"' in markup
    assert 'id="summaryDeleteTripButton"' not in markup
    assert 'id="pickTrollingSpreadButton"' in markup
    assert 'id="pickSavedSetupButton"' in markup
    assert 'id="trollingSpreadPickerDialog"' in markup
    assert 'id="savedSetupPickerDialog"' in markup
    assert 'id="defaultTrollingSpreadId"' in markup
    assert 'id="savedSetupMethodSections"' in markup
    assert "Trolling default" in markup
    assert 'id="defaultTrollingSpreadTargetSpecies"' not in markup
    assert 'data-import-noaa-probe-profile' in markup
    assert 'id="probeProfileImportStatus"' in markup
    assert 'id="probeProfileSourceNote"' in markup
    assert 'data-choose-probe-profile-location' in markup
    assert 'id="probeProfileLocationDialog"' in markup
    assert 'id="checklistsPanel"' in markup
    assert 'id="wikiPanel"' in markup
    assert 'id="wikiSearch"' in markup
    assert 'id="settingsWikiButton"' in markup
    assert 'class="settings-tab" id="settingsWikiButton"' in markup
    assert 'data-settings-tab="map-pins"' in markup
    assert 'id="speciesMapColorRows"' in markup
    assert 'id="wikiViewButton"' not in markup
    assert 'id="wiki-mobile"' in markup
    assert 'href="#wiki-mobile"' in markup
    assert "Mobile-only features" in markup
    assert "Trip Basics field guide" in markup
    assert "Choose map point" in markup
    assert "Autofill from Queue" in markup
    assert 'id="loadSpreadTemplateButton"' not in markup
    assert 'id="saveSpreadTemplateButton"' not in markup
    assert 'id="settingsSpreadTemplateSelect"' not in markup
    assert 'id="spreadTemplateDialog"' not in markup
    assert 'id="tripTemplatesDialog"' not in markup
    assert 'id="tripChecklistItems"' not in markup
    assert 'id="catchRowTemplate"' in markup
    assert 'class="catch-deepest-rigger"' in markup
    assert 'class="trip-gear-deepest-rigger"' not in markup
    assert "Previous standalone leaderboard markup" not in markup
    assert "{% include" not in markup

    ids = re.findall(r'\bid="([^"]+)"', markup)
    assert len(ids) == len(set(ids)), "Rendered frontend contains duplicate element IDs"


def test_checklists_route_renders_the_app(fish) -> None:
    response = fish.client.get("/checklists")

    assert response.status_code == 200
    assert 'id="checklistsPanel"' in response.get_data(as_text=True)


def test_wiki_route_renders_the_app(fish) -> None:
    response = fish.client.get("/wiki")

    assert response.status_code == 200
    markup = response.get_data(as_text=True)
    assert 'id="wikiPanel"' in markup
    assert 'id="wikiSearch"' in markup
    assert 'id="wikiExpandAllButton"' in markup
    assert "Setup field guide" in markup


def test_shell_loads_only_the_local_bundle(fish) -> None:
    markup = fish.client.get("/trips").get_data(as_text=True)

    assert re.search(r'<link rel="stylesheet" href="static/dist/app-styles\.css(\?v=\w+)?" />', markup)
    assert re.search(r'<script src="static/dist/app\.js(\?v=\w+)?"></script>', markup)
    assert "static/js/" not in markup
    for host in ("unpkg.com", "cdnjs.cloudflare.com", "fonts.googleapis.com", "fonts.gstatic.com"):
        assert host not in markup


def test_standalone_renders_the_built_bundle() -> None:
    if not (ROOT / "static" / "dist" / "manifest.json").is_file():
        import pytest

        pytest.skip("frontend bundle not built (npm run build)")
    result = subprocess.run(
        [sys.executable, str(ROOT / "scripts/build-standalone.py")],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, result.stdout + result.stderr
    standalone = (ROOT / "standalone.html").read_text(encoding="utf-8")
    assert "Generated by scripts/build-standalone.py" in standalone
    assert "static/dist/app.js" in standalone
