import { useMemo, useState } from "react";
import { Alert, Image, Pressable, StyleSheet, Text, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { Badge, DangerButton, EmptyState, Field, Panel, PrimaryButton, Screen, SecondaryButton, TopBar } from "../../components/ui";
import { id } from "../../domain/logbook";
import { setupMinutes } from "../../domain/services/duration";
import { useLogbook } from "../../state/logbook-context";
import { chooseMedia } from "../../storage/media";
import { tokens } from "../../theme/tokens";

type Kind="lures"|"flashers"|"rods"|"reels"|"rodReelCombos";
const labels:Record<Kind,string>={lures:"Baits",flashers:"Flashers",rods:"Rods",reels:"Reels",rodReelCombos:"Combos"};
const fields:Record<Kind,Array<[string,string]>>={
  lures:[["name","Name"],["type","Type"],["brand","Brand / model"],["color","Color"],["bladeType","Blade type"],["spoonSize","Spoon size"],["notes","Notes"]],
  flashers:[["name","Name"],["type","Type"],["brand","Brand / model"],["color","Color"],["notes","Notes"]],
  rods:[["shortName","Short name"],["type","Type"],["brand","Brand"],["name","Model"],["length","Length"],["power","Power"],["action","Action"],["lureRating","Lure rating"],["purchaseAmount","Purchase amount"],["dateBought","Date bought"],["notes","Notes"]],
  reels:[["shortName","Short name"],["style","Style"],["brand","Brand"],["name","Model"],["size","Size"],["weight","Weight"],["gearRatio","Gear ratio"],["retrieveRate","Retrieve rate"],["maxDrag","Max drag"],["monoCapacity","Mono capacity"],["braidCapacity","Braid capacity"],["purchaseAmount","Purchase amount"],["dateBought","Date bought"],["notes","Notes"]],
  rodReelCombos:[["shortName","Short name"],["rodId","Rod"],["reelId","Reel"],["notes","Notes"]],
};
export function GearScreen(){
  const params=useLocalSearchParams<{kind:string}>(); const kind=(Object.keys(labels).includes(params.kind)?params.kind:"lures") as Kind;
  const {logbook,update}=useLogbook(); const router=useRouter(); const items=logbook[kind] as Array<Record<string,any>>;
  const close=()=>router.canGoBack()?router.back():router.replace("/(tabs)/trips");
  const [query,setQuery]=useState(""),[editing,setEditing]=useState<Record<string,any>|null>(null);
  const results=useMemo(()=>items.filter(item=>JSON.stringify(item).toLowerCase().includes(query.toLowerCase())),[items,query]);
  const usage=(itemId:string)=>logbook.trips.reduce((n,t)=>n+t.gearUsed.filter(line=>Object.values(line).includes(itemId)).length+t.catches.filter(fish=>Object.values(fish).includes(itemId)).length+t.lostFish.filter(fish=>Object.values(fish).includes(itemId)).length,0)+logbook.rodReelCombos.filter(combo=>Object.values(combo).includes(itemId)).length;
  const performance=(itemId:string)=>{const lines=logbook.trips.flatMap(trip=>trip.gearUsed.filter(line=>Object.values(line).includes(itemId)).map(line=>({trip,line}))),ids=new Set(lines.map(item=>item.line.id)),records=logbook.trips.flatMap(trip=>trip.catches.filter(fish=>(fish.setupLineId&&ids.has(fish.setupLineId))||Object.values(fish).includes(itemId)).map(fish=>({trip,fish}))),catches=Array.from(new Map(records.map(item=>[item.fish.id,item])).values()),minutes=lines.reduce((sum,item)=>sum+setupMinutes(item.line),0),species=Array.from(new Set(catches.map(item=>item.fish.species).filter(Boolean)));return {fish:catches.length,trips:new Set([...lines.map(item=>item.trip.id),...catches.map(item=>item.trip.id)]).size,rate:minutes?catches.length/(minutes/60):null,species:species.slice(0,3).join(", ")}};
  const save=async()=>{if(!editing)return;const next=items.some(i=>i.id===editing.id)?items.map(i=>i.id===editing.id?editing:i):[...items,editing];await update({...logbook,[kind]:next});setEditing(null)};
  const remove=(item:Record<string,any>)=>{const count=usage(item.id);if(count){Alert.alert("Gear is in use",`${item.name||item.shortName} is referenced by ${count} setup records and cannot be deleted.`);return}Alert.alert("Delete gear?","This cannot be undone.",[{text:"Cancel",style:"cancel"},{text:"Delete",style:"destructive",onPress:()=>update({...logbook,[kind]:items.filter(i=>i.id!==item.id)})}])};
  const attach=async()=>{const media=await chooseMedia(kind==="lures"?"lures":kind==="flashers"?"flashers":kind==="reels"?"reels":"rods");if(media)setEditing(item=>item?{...item,image:media.uri,imageFilename:media.filename,media:[...(item.media||[]),media]}:item)};
  return <Screen><TopBar title={labels[kind]} subtitle="Gear inventory and performance" actions={<View style={s.actions}><SecondaryButton label="Back" compact onPress={close}/><PrimaryButton label={`New ${labels[kind].replace(/s$/,"")}`} compact onPress={()=>setEditing({id:id(),name:"",shortName:"",lineHistory:kind==="reels"?[]:undefined})}/></View>}/>
    <View style={s.kinds}>{(Object.keys(labels) as Kind[]).map(value=><Pressable key={value} onPress={()=>router.replace(`/gear/${value}`)} style={[s.kind,value===kind&&s.active]}><Text style={[s.kindText,value===kind&&s.activeText]}>{labels[value]}</Text></Pressable>)}</View>
    <Field label="Search" value={query} onChangeText={setQuery} placeholder="Name, brand, type, color"/>
    {editing?<Panel title={editing.id&&items.some(i=>i.id===editing.id)?"Edit gear":"Add gear"}>{editing.image?<Image source={{uri:editing.image}} style={s.hero}/>:null}<View style={s.form}>{fields[kind].map(([key,label])=><Field key={key} label={label} value={String(editing[key]||"")} onChangeText={value=>setEditing(item=>({...item,[key]:value}))} multiline={key==="notes"}/>)}</View>{kind==="reels"?<LineHistory entries={editing.lineHistory||[]} setEntries={lineHistory=>setEditing(item=>({...item,lineHistory}))}/>:null}<View style={s.actions}><SecondaryButton label="Attach Media" onPress={attach}/><SecondaryButton label="Cancel" onPress={()=>setEditing(null)}/><PrimaryButton label="Save Gear" onPress={save}/></View></Panel>:null}
    {!results.length?<EmptyState title={`No ${labels[kind].toLowerCase()} saved`} description="Add reusable gear to make trip setup and catch entry faster."/>:<View style={s.list}>{results.map(item=>{const stats=performance(item.id);return <Pressable key={item.id} onPress={()=>setEditing(structuredClone(item))} style={s.row}>{item.image||item.imagePath?<Image source={{uri:item.image||item.imagePath}} style={s.thumb}/>:<View style={s.placeholder}/>}<View style={{flex:1}}><Text style={s.title}>{item.name||item.shortName||"Unnamed"}</Text><Text style={s.meta}>{[item.type||item.style,item.brand,item.color||item.length||item.size].filter(Boolean).join(" · ")||"No specifications"}</Text><View style={s.performance}><Text style={s.performanceValue}>{stats.fish} fish</Text><Text style={s.meta}>{stats.trips} trips</Text><Text style={s.meta}>{stats.rate===null?"Rate unavailable":`${stats.rate.toFixed(2)} fish/hr`}</Text></View>{stats.species?<Text style={s.species}>{stats.species}</Text>:null}<View style={s.badges}><Badge tone="neutral">{usage(item.id)} uses</Badge>{item.lineHistory?.length?<Badge>{item.lineHistory.length} line records</Badge>:null}</View></View><DangerButton label="Delete" compact onPress={()=>remove(item)}/></Pressable>})}</View>}
  </Screen>
}
function LineHistory({entries,setEntries}:{entries:Array<Record<string,any>>;setEntries:(items:Array<Record<string,any>>)=>void}){const add=()=>setEntries([...entries,{id:id(),spooledDate:new Date().toISOString().slice(0,10),discardedDate:"",type:"",brand:"",name:"",weight:"",diameterIn:"",diameterMm:"",color:"",monoBacking:"",notes:""}]);const patch=(entryId:string,key:string,value:string)=>setEntries(entries.map(entry=>entry.id===entryId?{...entry,[key]:value}:entry));return <View style={s.form}><View style={s.lineHead}><Text style={s.sectionTitle}>Line Tracker</Text><SecondaryButton label="Add Line" compact onPress={add}/></View>{entries.map((entry,index)=><View key={entry.id} style={s.lineCard}><Text style={s.title}>Line record {index+1}</Text><View style={s.lineGrid}>{[["spooledDate","Spooled date"],["discardedDate","Discarded date"],["type","Type"],["brand","Brand"],["name","Name"],["weight","Weight"],["diameterIn","Diameter (in)"],["diameterMm","Diameter (mm)"],["color","Color"],["monoBacking","Mono backing"],["notes","Notes"]].map(([key,label])=><Field key={key} label={label} value={String(entry[key]||"")} onChangeText={value=>patch(entry.id,key,value)}/>)}</View><DangerButton label="Remove Line Record" compact onPress={()=>setEntries(entries.filter(item=>item.id!==entry.id))}/></View>)}</View>}
const s=StyleSheet.create({actions:{flexDirection:"row",flexWrap:"wrap",gap:8},kinds:{flexDirection:"row",flexWrap:"wrap",gap:8},kind:{paddingVertical:9,paddingHorizontal:13,borderWidth:1,borderColor:tokens.color.line,borderRadius:7,backgroundColor:tokens.color.field},active:{backgroundColor:tokens.color.activeBackground,borderColor:tokens.color.chipLine},kindText:{color:tokens.color.text,fontSize:12,fontWeight:"800"},activeText:{color:tokens.color.activeText},form:{gap:12},list:{borderWidth:1,borderColor:tokens.color.line,borderRadius:8,overflow:"hidden"},row:{flexDirection:"row",alignItems:"flex-start",gap:12,padding:13,backgroundColor:tokens.color.panel,borderBottomWidth:1,borderColor:tokens.color.line},thumb:{width:58,height:58,borderRadius:7,backgroundColor:tokens.color.black},placeholder:{width:58,height:58,borderRadius:7,backgroundColor:tokens.color.panelSoft,borderWidth:1,borderColor:tokens.color.line},hero:{width:"100%",height:180,borderRadius:8,backgroundColor:tokens.color.black},title:{color:tokens.color.text,fontWeight:"800",fontSize:15},meta:{color:tokens.color.muted,fontSize:12,marginTop:3},performance:{flexDirection:"row",flexWrap:"wrap",gap:10,marginTop:7},performanceValue:{color:tokens.color.greenDark,fontSize:12,fontWeight:"900"},species:{color:tokens.color.text,fontSize:11,marginTop:4},badges:{flexDirection:"row",gap:6,marginTop:7},lineHead:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginTop:8},sectionTitle:{color:tokens.color.text,fontSize:18,fontWeight:"800"},lineCard:{gap:10,padding:12,borderWidth:1,borderColor:tokens.color.line,borderRadius:8,backgroundColor:tokens.color.panelSoft},lineGrid:{flexDirection:"row",flexWrap:"wrap",gap:10}});
