import { useDeferredValue, useMemo, useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useRouter } from "expo-router";
import { Badge, EmptyState, MetricStrip, PrimaryButton, Screen, SecondaryButton, Table, TableCell, TableRow, TopBar, useIsTablet } from "../../components/ui";
import { tripDurationHours } from "../../domain/logbook";
import type { Trip } from "../../domain/types";
import { useLogbook } from "../../state/logbook-context";
import { tokens } from "../../theme/tokens";

type Sort = "Newest first" | "Oldest first" | "Best catch rate" | "Most fish" | "Most hours";
const sorts: Sort[] = ["Newest first","Oldest first","Best catch rate","Most fish","Most hours"];
const next = (items:string[], current:string) => items[(items.indexOf(current)+1)%items.length];
const rate = (trip:Trip) => tripDurationHours(trip) ? trip.catches.length/tripDurationHours(trip) : 0;

export function TripsScreen() {
  const {logbook,ready,totals,activeTrip} = useLogbook();
  const router = useRouter();
  const tablet = useIsTablet();
  const [query,setQuery] = useState(""), [target,setTarget] = useState("All targets"), [method,setMethod] = useState("All methods"), [year,setYear] = useState("All years"), [sort,setSort] = useState<Sort>("Newest first");
  const [filtersOpen,setFiltersOpen] = useState(false);
  const deferredQuery = useDeferredValue(query.trim().toLowerCase());
  const years = useMemo(()=>["All years",...Array.from(new Set(logbook.trips.map(t=>t.date.slice(0,4)))).sort().reverse()],[logbook.trips]);
  const trips = useMemo(()=>{
    const filtered=logbook.trips.filter(trip=>{
      const haystack=[trip.title,trip.location,trip.launch,trip.targetSpecies,trip.method,trip.notes,...trip.catches.map(c=>c.species),...trip.catches.map(c=>String(c.lureName||""))].join(" ").toLowerCase();
      return (!deferredQuery||haystack.includes(deferredQuery))&&(target==="All targets"||trip.targetSpecies===target)&&(method==="All methods"||trip.method===method)&&(year==="All years"||trip.date.startsWith(year));
    });
    return filtered.sort((a,b)=>sort==="Oldest first"?a.date.localeCompare(b.date):sort==="Most fish"?b.catches.length-a.catches.length:sort==="Most hours"?tripDurationHours(b)-tripDurationHours(a):sort==="Best catch rate"?rate(b)-rate(a):b.date.localeCompare(a.date));
  },[logbook.trips,deferredQuery,target,method,year,sort]);
  const waterbodies=new Set(logbook.trips.map(t=>t.location).filter(Boolean)).size;
  const filtersActive=Boolean(query)||target!=="All targets"||method!=="All methods"||year!=="All years"||sort!=="Newest first";
  const clearFilters=()=>{setQuery("");setTarget("All targets");setMethod("All methods");setYear("All years");setSort("Newest first");};
  return <Screen>
    <TopBar title="Trips" actions={<View style={s.headerActions}><Pressable accessibilityRole="button" accessibilityLabel={filtersOpen?"Close trip search and filters":"Open trip search and filters"} accessibilityState={{expanded:filtersOpen}} onPress={()=>setFiltersOpen(open=>!open)} style={({pressed})=>[s.searchTrigger,(filtersOpen||filtersActive)&&s.searchTriggerActive,pressed&&s.pressed]}><SearchIcon/><View style={[s.searchIndicator,(filtersOpen||filtersActive)&&s.searchIndicatorActive]}/></Pressable></View>}/>
    {tablet||filtersOpen?<TripFilters query={query} setQuery={setQuery} target={target} setTarget={setTarget} method={method} setMethod={setMethod} year={year} setYear={setYear} sort={sort} setSort={setSort} logbook={logbook} years={years} showClear={filtersActive} onClear={clearFilters}/>:null}
    <MetricStrip metrics={[
      {label:"Trips",value:totals.trips},{label:"Fish",value:totals.landed},{label:"Hours",value:totals.hours.toFixed(1)},{label:"Fish / hr",value:totals.fishPerHour.toFixed(2)},
      ...(tablet?[{label:"Waterbodies",value:waterbodies}]:[])
    ]}/>
    <View style={s.tripActions}><PrimaryButton label={activeTrip?"Continue Live Trip":"Start Live Trip"} onPress={()=>activeTrip?router.push("/live"):router.push("/trip/new?mode=live")} style={s.tripAction}/><SecondaryButton label="Add Historical Trip" onPress={()=>router.push("/trip/new?mode=historical")} style={s.tripAction}/></View>
    {activeTrip?<Pressable onPress={()=>router.push("/live")} style={s.active}><View><Text style={s.activeLabel}>● LIVE · {activeTrip.linesSetTime||activeTrip.startTime}</Text><Text style={s.activeTitle}>{activeTrip.location||activeTrip.title}</Text><Text style={s.muted}>{activeTrip.method} · {activeTrip.catches.length} landed · {activeTrip.lostFish.length} lost · {activeTrip.gearUsed.filter(line=>!line.endTime).length} active lines</Text></View><Text style={s.continue}>Open ›</Text></Pressable>:null}
    {!ready?<EmptyState title="Opening your logbook…"/>:!trips.length?<EmptyState title={logbook.trips.length?"No matching trips":"No trips yet"} description={logbook.trips.length?"Change the filters or create a new trip.":"Start logging on the water or add a past trip. Everything is saved locally."}/>:tablet?
      <Table minWidth={850}><TableRow header><TableCell header width={110}>Date</TableCell><TableCell header width={140}>Location</TableCell><TableCell header width={140}>Launch / Area</TableCell><TableCell header width={180}>Title</TableCell><TableCell header width={140}>Target</TableCell><TableCell header width={110}>Method</TableCell><TableCell header width={70}>Hours</TableCell><TableCell header width={55}>Fish</TableCell><TableCell header width={60}>Rate</TableCell></TableRow>{trips.map(trip=><TableRow key={trip.id} onPress={()=>router.push(`/trip/${trip.id}`)}><TableCell width={110}>{trip.date}</TableCell><TableCell width={140}>{trip.location||"—"}</TableCell><TableCell width={140}>{trip.launch||"—"}</TableCell><TableCell width={180}>{trip.title}</TableCell><TableCell width={140}>{trip.targetSpecies||"—"}</TableCell><TableCell width={110}>{trip.method||"—"}</TableCell><TableCell width={70}>{tripDurationHours(trip).toFixed(2)}</TableCell><TableCell width={55}>{trip.catches.length}</TableCell><TableCell width={60}>{rate(trip).toFixed(2)}</TableCell></TableRow>)}</Table>:
      <View style={s.list}>{trips.map(trip=><Pressable key={trip.id} onPress={()=>router.push(`/trip/${trip.id}`)} style={({pressed})=>[s.row,pressed&&s.pressed]}><View style={s.rowTop}><Text style={s.date}>{new Date(`${trip.date}T12:00:00`).toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"})}</Text><Text style={s.duration}>{tripDurationHours(trip).toFixed(1)}h · ›</Text></View><Text style={s.tripTitle}>{trip.title}</Text><View style={s.identity}><View style={s.identityColumn}><Text style={s.location}>{trip.location||"No waterbody"}</Text><Text style={s.muted}>{trip.launch||"No launch / area"}</Text></View><View style={s.identityColumn}><Text style={s.location}>{trip.targetSpecies||"No target"}</Text><Text style={s.muted}>{trip.method||"No method"}</Text></View></View><View style={s.outcomes}><View style={s.outcome}><Text style={s.outcomeLabel}>LANDED</Text><Text style={s.fish}>{trip.catches.length}</Text></View><View style={s.outcome}><Text style={s.outcomeLabel}>LOST</Text><Text style={s.lost}>{trip.lostFish.length}</Text></View><View style={s.outcome}><Text style={s.outcomeLabel}>FISH / HR</Text><Text style={s.outcomeValue}>{rate(trip).toFixed(2)}</Text></View></View><View style={s.conditions}><Text style={s.muted}>{[trip.weather,trip.waterTemp?`Water ${trip.waterTemp}°`:"",trip.wind,trip.waterClarity].filter(Boolean).join(" · ")||"Conditions not logged"}</Text></View><View style={s.badges}>{trip.intent?<Badge tone="neutral">{trip.intent}</Badge>:null}{trip.tripRating?<Badge tone={String(trip.tripRating).toLowerCase()==="bad"?"danger":"success"}>{trip.tripRating}</Badge>:null}</View></Pressable>)}</View>}
  </Screen>;
}

function TripFilters({query,setQuery,target,setTarget,method,setMethod,year,setYear,sort,setSort,logbook,years,showClear,onClear}:{query:string;setQuery:(value:string)=>void;target:string;setTarget:(value:string)=>void;method:string;setMethod:(value:string)=>void;year:string;setYear:(value:string)=>void;sort:Sort;setSort:(value:Sort)=>void;logbook:ReturnType<typeof useLogbook>["logbook"];years:string[];showClear:boolean;onClear:()=>void}){return <View accessibilityLabel="Trip search and filters" style={s.filters}><View style={s.searchWrap}><View style={s.filterHeading}><Text style={s.label}>SEARCH TRIPS</Text>{showClear?<Pressable accessibilityRole="button" onPress={onClear} hitSlop={8}><Text style={s.clear}>Clear</Text></Pressable>:null}</View><View style={s.searchField}><SearchIcon muted/><TextInput autoFocus value={query} onChangeText={setQuery} placeholder="Location, species, lure, notes" placeholderTextColor={tokens.color.muted} style={s.search}/>{query?<Pressable accessibilityRole="button" accessibilityLabel="Clear search" onPress={()=>setQuery("")} hitSlop={8}><Text style={s.clearSearch}>×</Text></Pressable>:null}</View></View><View style={s.filterGrid}><Filter label="TARGET" value={target} onPress={()=>setTarget(next(["All targets",...logbook.species],target))}/><Filter label="METHOD" value={method} onPress={()=>setMethod(next(["All methods",...logbook.methods],method))}/><Filter label="YEAR" value={year} onPress={()=>setYear(next(years,year))}/><Filter label="SORT" value={sort} onPress={()=>setSort(next(sorts,sort) as Sort)} wide/></View></View>}
function Filter({label,value,onPress,wide=false}:{label:string;value:string;onPress:()=>void;wide?:boolean}){return <View style={[s.filter,wide&&s.filterWide]}><Text style={s.label}>{label}</Text><SecondaryButton label={value} onPress={onPress} compact style={s.filterButton}/></View>}
function SearchIcon({muted=false}:{muted?:boolean}){return <View style={[s.searchIcon,s.pointerEventsNone]}><View style={[s.searchIconCircle,muted&&s.searchIconCircleMuted]}/><View style={[s.searchIconHandle,muted&&s.searchIconHandleMuted]}/></View>}
const s=StyleSheet.create({
  headerActions:{flexDirection:"row",alignItems:"center",gap:8},searchTrigger:{width:34,height:30,borderWidth:1,borderColor:tokens.color.line,borderRadius:7,backgroundColor:tokens.color.panelSoft,alignItems:"center",justifyContent:"center"},searchTriggerActive:{borderColor:tokens.color.chipLine,backgroundColor:tokens.color.activeBackground},searchIndicator:{position:"absolute",right:4,top:4,width:5,height:5,borderRadius:3,backgroundColor:"transparent"},searchIndicatorActive:{backgroundColor:tokens.color.green},searchIcon:{width:17,height:17,position:"relative",alignItems:"center",justifyContent:"center"},pointerEventsNone:{pointerEvents:"none"},searchIconCircle:{position:"absolute",top:1,left:1,width:10,height:10,borderWidth:1.8,borderColor:tokens.color.text,borderRadius:10},searchIconCircleMuted:{borderColor:tokens.color.muted},searchIconHandle:{position:"absolute",width:7,height:1.8,borderRadius:2,backgroundColor:tokens.color.text,transform:[{rotate:"45deg"}],right:0,bottom:2},searchIconHandleMuted:{backgroundColor:tokens.color.muted},
  filters:{gap:14,backgroundColor:tokens.color.panel,borderColor:tokens.color.line,borderWidth:1,borderRadius:10,padding:14},searchWrap:{gap:7},filterHeading:{flexDirection:"row",alignItems:"center",justifyContent:"space-between"},filterGrid:{flexDirection:"row",flexWrap:"wrap",gap:10},filter:{minWidth:132,flex:1,gap:6},filterWide:{flexBasis:"100%"},label:{color:tokens.color.muted,fontSize:11,fontWeight:"900",letterSpacing:.4},searchField:{height:42,flexDirection:"row",alignItems:"center",gap:9,borderWidth:1,borderColor:tokens.color.line,borderRadius:8,backgroundColor:tokens.color.field,paddingHorizontal:12},search:{flex:1,height:"100%",color:tokens.color.text,fontSize:15},clear:{color:tokens.color.greenDark,fontSize:12,fontWeight:"800"},clearSearch:{color:tokens.color.muted,fontSize:22,lineHeight:22},filterButton:{alignItems:"flex-start"},
  tripActions:{flexDirection:"row",gap:10},tripAction:{flex:1,minHeight:52},list:{borderWidth:1,borderColor:tokens.color.line,borderRadius:8,overflow:"hidden"},row:{padding:15,backgroundColor:tokens.color.panel,borderBottomWidth:1,borderColor:tokens.color.line,gap:8},pressed:{backgroundColor:tokens.color.hover},rowTop:{flexDirection:"row",justifyContent:"space-between"},date:{color:tokens.color.muted,fontSize:12,fontWeight:"700"},duration:{color:tokens.color.muted,fontSize:12},tripTitle:{color:tokens.color.text,fontSize:17,fontWeight:"800"},identity:{flexDirection:"row",gap:14},identityColumn:{flex:1,gap:3},location:{color:tokens.color.text,fontSize:14,fontWeight:"700"},outcomes:{flexDirection:"row",borderTopWidth:1,borderBottomWidth:1,borderColor:tokens.color.line,paddingVertical:8},outcome:{flex:1,alignItems:"center",gap:2,borderRightWidth:1,borderRightColor:tokens.color.line},outcomeLabel:{color:tokens.color.muted,fontSize:9,fontWeight:"900",letterSpacing:.4},outcomeValue:{color:tokens.color.text,fontWeight:"900"},lost:{color:tokens.color.red,fontWeight:"900"},conditions:{minHeight:20,justifyContent:"center"},badges:{flexDirection:"row",flexWrap:"wrap",gap:6},muted:{color:tokens.color.muted,fontSize:12},fish:{color:tokens.color.greenDark,fontWeight:"900"},active:{backgroundColor:tokens.color.activeBackground,borderWidth:1,borderColor:tokens.color.green,borderRadius:8,padding:15,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},activeLabel:{color:tokens.color.green,fontSize:11,fontWeight:"900"},activeTitle:{color:tokens.color.text,fontSize:17,fontWeight:"800"},continue:{color:tokens.color.greenDark,fontWeight:"900"},
});
