import { useState } from "react";
import { Image, LayoutChangeEvent, StyleSheet, Text, View } from "react-native";
import { fishCount } from "../../domain/services/duration";
import { gearName } from "../../domain/services/setup-resolution";
import type { Logbook, SetupLine, Trip } from "../../domain/types";

type Point = { x: number; y: number };
const boat = require("../../../assets/trolling-boat.png");
const canonical = (value?: string) => String(value || "").toLowerCase().replaceAll(" ", "-");
const markerType = (line: SetupLine) => { const presentation = canonical(line.presentation); if (presentation.includes("board")) return "board"; if (presentation.includes("diver")) return "diver"; if (presentation === "chute-rod" || presentation === "flatline") return "chute"; return "rigger"; };
const order = (line: SetupLine) => { const presentation = canonical(line.presentation); return presentation.includes("outside") ? 0 : presentation.includes("inside") ? 1 : presentation.includes("high") ? 2 : presentation.includes("low") ? 3 : presentation.includes("downrigger") || presentation === "cheater" ? 4 : 2; };
const labelOrder = (line: SetupLine) => 5 - order(line);

export function TrollingSpreadDiagram({ trip, logbook }: { trip: Trip; logbook: Logbook }) {
  const [size, setSize] = useState({ width: 0, height: 0 });
  const active = trip.gearUsed;
  const onLayout = (event: LayoutChangeEvent) => setSize(event.nativeEvent.layout);
  return <View onLayout={onLayout} style={s.canvas}><Image source={boat} resizeMode="contain" style={s.boat}/>{size.width ? <SpreadLines lines={active} trip={trip} logbook={logbook} width={size.width} height={size.height}/> : null}<Text style={s.direction}>↑ TRAVEL</Text></View>;
}

function SpreadLines({ lines, trip, logbook, width, height }: { lines: SetupLine[]; trip: Trip; logbook: Logbook; width: number; height: number }) {
  const groups = ["port", "center", "starboard"].flatMap(side => lines.filter(line => (line.side || "center").toLowerCase() === side).sort((a, b) => labelOrder(a) - labelOrder(b)).map((line, index) => ({ line, side, index })));
  return <>{groups.map(({ line, side, index }) => { const path = pathFor(line, side, index, width, height); return <RodPath key={line.id} line={line} side={side} path={path} width={width} trip={trip} logbook={logbook}/>; })}</>;
}
function pathFor(line: SetupLine, side: string, index: number, width: number, height: number) { const type = markerType(line); if (side === "center" || type === "chute") { const source = { x: width / 2, y: 242 }, endpoint = { x: width / 2, y: Math.min(height - 56, 370 + index * 52) }; return { source, endpoint, bend: null as Point | null }; } const direction = side === "port" ? -1 : 1, slot = order(line); if (type === "rigger") { const source = { x: width / 2 + direction * 56, y: 219 }, endpoint = { x: width / 2 + direction * 56, y: Math.min(height - 56, 350 + index * 52) }; return { source, endpoint, bend: null as Point | null }; } const source = { x: width / 2 + direction * 49, y: 126 + slot * 20 }, laneX = direction < 0 ? 28 + slot * 20 : width - 28 - slot * 20, bend = { x: laneX, y: source.y + 72 }, endpoint = { x: laneX, y: Math.min(height - 56, 350 + index * 52) }; return { source, endpoint, bend }; }
function Segment({ from, to }: { from: Point; to: Point }) { const dx = to.x - from.x, dy = to.y - from.y, distance = Math.sqrt(dx * dx + dy * dy), angle = `${Math.atan2(dy, dx) * 180 / Math.PI}deg`; return <View style={[s.line, { width: distance, left: (from.x + to.x - distance) / 2, top: (from.y + to.y) / 2 - 1, transform: [{ rotate: angle }] }]}/>; }
function RodPath({ line, side, path, width, trip, logbook }: { line: SetupLine; side: string; path: { source: Point; endpoint: Point; bend: Point | null }; width: number; trip: Trip; logbook: Logbook }) { const landed = trip.catches.filter(fish => fish.setupLineId === line.id).reduce((sum, fish) => sum + fishCount(fish), 0); const lost = trip.lostFish.filter(fish => fish.setupLineId === line.id).length, type = markerType(line), cardLeft = side === "port" ? 8 : side === "starboard" ? width - 122 : width / 2 - 57; return <><Segment from={path.source} to={path.bend || path.endpoint}/>{path.bend ? <><Segment from={path.bend} to={path.endpoint}/><View style={[s.marker, markerStyle(type), { left: path.bend.x - 7, top: path.bend.y - 7 }]}/></> : type === "chute" ? <View style={[s.marker,s.chute,{left:path.endpoint.x-7,top:path.endpoint.y-7}]}/> : null}<View style={[s.card,{left:cardLeft,top:path.endpoint.y-18}]}><Text numberOfLines={1} style={s.cardTitle}>{line.lineLabel || line.presentation || "Rod"}</Text><Text numberOfLines={1} style={s.cardDetail}>{gearName(logbook, "lure", line.lureId) || "No lure"}</Text>{landed || lost ? <Text style={s.cardStat}>{landed ? `${landed} landed` : ""}{landed && lost ? " · " : ""}{lost ? `${lost} lost` : ""}</Text> : null}</View></> }
function markerStyle(type: string) { return type === "board" ? s.board : type === "diver" ? s.diver : type === "chute" ? s.chute : s.rigger; }
const s = StyleSheet.create({ canvas:{height:540,position:"relative",overflow:"hidden",borderRadius:12,backgroundColor:"#dff3fb",borderWidth:1,borderColor:"#9bc5d4"},boat:{position:"absolute",width:255,height:150,top:73,left:"50%",marginLeft:-127,transform:[{rotate:"90deg"}]},direction:{position:"absolute",top:6,left:"50%",marginLeft:-28,color:"#31505f",fontSize:9,fontWeight:"900",letterSpacing:.7},line:{position:"absolute",height:2,backgroundColor:"#3b5563",borderRadius:2},marker:{position:"absolute",width:14,height:14,borderWidth:2,borderColor:"#fff",backgroundColor:"#475569"},board:{width:11,height:22,borderRadius:3,borderColor:"#92400e",backgroundColor:"#f59e0b",transform:[{rotate:"90deg"}]},diver:{borderRadius:8,backgroundColor:"#111827"},chute:{borderRadius:8,backgroundColor:"#0f766e"},rigger:{transform:[{rotate:"45deg"}]},card:{position:"absolute",width:114,minHeight:35,paddingHorizontal:6,paddingVertical:4,borderRadius:6,backgroundColor:"rgba(255,255,255,.94)",borderWidth:1,borderColor:"#aac9d5"},cardTitle:{color:"#15222b",fontSize:10,fontWeight:"900"},cardDetail:{color:"#3b5563",fontSize:9,fontWeight:"700",marginTop:1},cardStat:{color:"#08734d",fontSize:8,fontWeight:"900",marginTop:2} });
