import { useMemo, useState } from "react";
import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import Svg, { Circle, Line, Path } from "react-native-svg";
import { EmptyState, PrimaryButton, Screen, SecondaryButton, TopBar } from "../../components/ui";
import { buildAnalytics, measurementBuckets } from "../../domain/analytics";
import type { Performance, Scope } from "../../domain/services/analytics-reports";
import type { Logbook, Trip } from "../../domain/types";
import { tripHours } from "../../domain/services/duration";
import { useLogbook } from "../../state/logbook-context";
import { tokens } from "../../theme/tokens";

type GroupName = "Catch results & patterns" | "Lure performance" | "Trolling stats" | "Speed, spread & water column" | "Trip patterns" | "Conditions";
type DatePreset = "all" | "season" | "30" | "90";
type SimpleRow = { name: string; fish: number; trips: number; detail?: string };

const groups: Array<{ name: GroupName; description: string }> = [
  { name: "Catch results & patterns", description: "Outcome, species mix, release rate, target success, and bite timing" },
  { name: "Lure performance", description: "Time-adjusted lure return, plus trolling flashers and combinations" },
  { name: "Trolling stats", description: "Port vs starboard, method, direction, flasher, combination, FOW, and depth" },
  { name: "Speed, spread & water column", description: "Ball speed, GPS speed, shaker, spread distance, and probe temperature" },
  { name: "Trip patterns", description: "Method, location, angler, month, fishing confidence, and trip rating" },
  { name: "Conditions", description: "Water clarity, weather tag, wind, pressure, cloud cover, fronts, and moon windows" },
];

const cycle = (values: string[], value?: string) => values[(values.indexOf(value || values[0]) + 1) % values.length];
const number = (value: unknown) => { const match = String(value ?? "").match(/-?\d+(\.\d+)?/); return match ? Number(match[0]) : 0; };
const fishOnTrip = (trip: Trip) => trip.catches.reduce((sum, item) => sum + Math.max(1, number(item.quantity)), 0);
const dateLabel: Record<DatePreset, string> = { all: "All time", season: "This season", "30": "Last 30 days", "90": "Last 90 days" };

export function StatsScreen() {
  const { logbook } = useLogbook();
  const [filtersOpen, setFiltersOpen] = useState(false);
  const [datePreset, setDatePreset] = useState<DatePreset>("all");
  const [scope, setScope] = useState<Scope>({});
  const [expanded, setExpanded] = useState<Set<GroupName>>(new Set());
  const datedScope = useMemo(() => withDatePreset(scope, datePreset, logbook), [scope, datePreset, logbook]);
  const data = useMemo(() => buildAnalytics(logbook, datedScope), [logbook, datedScope]);
  const activeFilters = Object.entries(scope).filter(([, value]) => Boolean(value) && !String(value).startsWith("All "));
  const bestTrip = useMemo(() => [...data.trips].sort((a, b) => fishOnTrip(b) - fishOnTrip(a))[0], [data.trips]);
  const scopeText = [dateLabel[datePreset], ...(activeFilters.length ? activeFilters.map(([, value]) => String(value)) : ["All methods"])].join(" / ");
  const toggle = (name: GroupName) => setExpanded(current => { const next = new Set(current); next.has(name) ? next.delete(name) : next.add(name); return next; });

  return <Screen contentContainerStyle={s.page}>
    <TopBar title="Stats" />
    <View style={s.scopeRow}>
      <View style={s.scopeCopy}><Text style={s.scopeLabel}>CURRENT SCOPE</Text><Text style={s.scopeText} numberOfLines={2}>{scopeText}</Text></View>
      <PrimaryButton compact label={`Filters${activeFilters.length ? ` · ${activeFilters.length}` : ""}`} onPress={() => setFiltersOpen(true)} />
    </View>
    {activeFilters.length ? <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.filterRail}>
      {activeFilters.map(([key, value]) => <Pressable accessibilityRole="button" key={key} onPress={() => setScope(current => ({ ...current, [key]: undefined }))} style={s.filterChip}><Text style={s.filterText}>{String(value)}  ×</Text></Pressable>)}
    </ScrollView> : null}
    <MetricGrid data={data} bestTrip={bestTrip} />
    <View style={s.overviewStack}>
      <AnalyticsCard title="Catch Overview"><CatchOverview trips={data.trips} /></AnalyticsCard>
      <AnalyticsCard title="Top Species"><CompactBars rows={data.species.slice(0, 7)} /></AnalyticsCard>
    </View>
    <View style={s.groupStack}>{groups.map(group => <View key={group.name}>
      <Pressable accessibilityRole="button" accessibilityState={{ expanded: expanded.has(group.name) }} onPress={() => toggle(group.name)} style={({ pressed }) => [s.groupHeader, pressed && s.pressed]}>
        <View style={s.groupCopy}><Text style={s.groupTitle}>{group.name}</Text><Text style={s.groupDescription}>{group.description}</Text></View><Text style={s.groupIcon}>{expanded.has(group.name) ? "−" : "+"}</Text>
      </Pressable>
      {expanded.has(group.name) ? <View style={s.groupBody}>{renderGroup(group.name, data, logbook)}</View> : null}
    </View>)}</View>
    <FilterSheet visible={filtersOpen} datePreset={datePreset} setDatePreset={setDatePreset} scope={scope} setScope={setScope} logbook={logbook} onClose={() => setFiltersOpen(false)} />
  </Screen>;
}

function MetricGrid({ data, bestTrip }: { data: ReturnType<typeof buildAnalytics>; bestTrip?: Trip }) {
  const interactions = data.summary.landed + data.summary.lost;
  const metrics = [
    { label: "Trips", value: data.summary.trips, detail: `${data.summary.hours.toFixed(2)} hours fished` },
    { label: "Landed fish", value: data.summary.landed, detail: `${data.summary.released} released · ${data.summary.kept} kept` },
    { label: "Fish / hour", value: data.summary.fishPerHour.toFixed(2), detail: `${data.summary.trips ? (data.summary.landed / data.summary.trips).toFixed(2) : "0"} fish / trip` },
    { label: "Landing rate", value: `${interactions ? (data.summary.landed / interactions * 100).toFixed(2) : "0"}%`, detail: `${data.summary.lost} lost fish` },
    { label: "Fishing hours", value: data.summary.hours.toFixed(2), detail: "" },
    { label: "Best trip", value: bestTrip ? `${fishOnTrip(bestTrip)} fish` : "—", detail: bestTrip ? new Date(`${bestTrip.date}T12:00:00`).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" }) : "No trips in scope" },
  ];
  return <View style={s.metricGrid}>{metrics.map(metric => <View key={metric.label} style={s.metricCard}><Text style={s.metricLabel}>{metric.label}</Text><Text style={s.metricValue}>{metric.value}</Text>{metric.detail ? <Text style={s.metricDetail}>{metric.detail}</Text> : null}</View>)}</View>;
}

function CatchOverview({ trips }: { trips: Trip[] }) {
  const points = [...trips].sort((a, b) => a.date.localeCompare(b.date)).map(trip => ({ label: new Date(`${trip.date}T12:00:00`).toLocaleDateString(undefined, { month: "short", day: "numeric" }), fish: fishOnTrip(trip), rate: tripHours(trip) ? fishOnTrip(trip) / tripHours(trip) : 0 }));
  if (!points.length) return <EmptyState title="No trips in scope" description="Add a trip or change the filters to see your catch trend." />;
  const width = 320, height = 154, left = 18, top = 12, bottom = 28, usableWidth = width - left * 2, usableHeight = height - top - bottom;
  const max = Math.max(1, ...points.flatMap(point => [point.fish, point.rate]));
  const xy = (value: number, index: number) => [left + (points.length === 1 ? usableWidth / 2 : index / (points.length - 1) * usableWidth), top + usableHeight - value / max * usableHeight] as const;
  const path = (key: "fish" | "rate") => points.map((point, index) => { const [x, y] = xy(point[key], index); return `${index ? "L" : "M"}${x} ${y}`; }).join(" ");
  return <View><Svg accessibilityLabel="Landed fish and fish per hour by trip" width="100%" height={height} viewBox={`0 0 ${width} ${height}`}>
    <Line x1={left} y1={top + usableHeight} x2={width - left} y2={top + usableHeight} stroke={tokens.color.line} strokeWidth="1" />
    <Path d={path("fish")} fill="none" stroke={tokens.color.green} strokeWidth="3" strokeLinejoin="round" /><Path d={path("rate")} fill="none" stroke={tokens.color.blue} strokeWidth="2" strokeLinejoin="round" />
    {points.map((point, index) => { const [x, y] = xy(point.fish, index); return <Circle key={`${point.label}-${index}`} cx={x} cy={y} r="3.5" fill={tokens.color.panel} stroke={tokens.color.greenDark} strokeWidth="2" />; })}
  </Svg><View style={s.legend}><Legend color={tokens.color.green} label="Landed" /><Legend color={tokens.color.blue} label="Fish / hr" /><Text style={s.legendRange}>{points[0].label} — {points.at(-1)?.label}</Text></View></View>;
}

function Legend({ color, label }: { color: string; label: string }) { return <View style={s.legendItem}><View style={[s.legendDot, { backgroundColor: color }]} /><Text style={s.legendText}>{label}</Text></View>; }
function AnalyticsCard({ title, children }: { title: string; children: React.ReactNode }) { return <View style={s.card}><View style={s.cardHeader}><Text style={s.cardTitle}>{title}</Text></View><View style={s.cardBody}>{children}</View></View>; }
function CompactBars({ rows }: { rows: Performance[] }) { const max = Math.max(1, ...rows.map(row => row.fish)); return rows.length ? <View>{rows.map(row => <View key={row.name} style={s.compactRow}><Text style={s.compactName} numberOfLines={1}>{row.name}</Text><View style={s.compactTrack}><View style={[s.compactFill, { width: `${row.fish / max * 100}%` }]} /></View><Text style={s.compactValue}>{row.fish}</Text></View>)}</View> : <EmptyState title="No species data" description="Catches in this scope will appear here." />; }

function renderGroup(name: GroupName, data: ReturnType<typeof buildAnalytics>, logbook: Logbook) {
  if (name === "Catch results & patterns") return <><AnalyticsCard title="Outcome Breakdown"><Outcome data={data} /></AnalyticsCard><AnalyticsCard title="Species Breakdown"><Ranked rows={data.species} /></AnalyticsCard><AnalyticsCard title="Lost Fish"><SimpleRows rows={lostRows(data)} empty="No lost fish in this scope" /></AnalyticsCard><AnalyticsCard title="Time Of Day"><Bites rows={data.biteWindows} /></AnalyticsCard><AnalyticsCard title="Release Patterns"><ReleaseRows data={data} /></AnalyticsCard></>;
  if (name === "Lure performance") return <><AnalyticsCard title="Lure Performance"><Ranked rows={data.lures} /></AnalyticsCard><AnalyticsCard title="Lure Usage Vs Fish Share"><Ranked rows={data.lures} share /></AnalyticsCard><AnalyticsCard title="Lure Spread Context"><Ranked rows={data.lures} detailLabel="Confidence reflects timed setup usage across trips." /></AnalyticsCard><AnalyticsCard title="Lure Type Performance"><SimpleRows rows={gearAttributeRows(data, logbook, "type")} empty="No lure type data in this scope" /></AnalyticsCard><AnalyticsCard title="Lure Color Performance"><SimpleRows rows={gearAttributeRows(data, logbook, "color")} empty="No lure color data in this scope" /></AnalyticsCard><AnalyticsCard title="Flasher Performance"><Ranked rows={data.flashers} /></AnalyticsCard><AnalyticsCard title="Lure + Flasher Combos"><Ranked rows={data.combos} /></AnalyticsCard></>;
  if (name === "Trolling stats") return <><AnalyticsCard title="Trolling Direction Performance"><Ranked rows={data.directions} /></AnalyticsCard><AnalyticsCard title="Line Side Performance"><Ranked rows={data.sides} /></AnalyticsCard><AnalyticsCard title="Trolling Method Performance"><Ranked rows={data.presentations} /></AnalyticsCard><AnalyticsCard title="FOW Fish Distribution"><Buckets rows={measurementBuckets(data.catches, "fowCaught", 10)} /></AnalyticsCard><AnalyticsCard title="Exact FOW Caught"><Buckets rows={measurementBuckets(data.catches, "fowCaught", 1)} /></AnalyticsCard><AnalyticsCard title="Depth Down"><Buckets rows={measurementBuckets(data.catches, "depthDown", 10)} /></AnalyticsCard></>;
  if (name === "Speed, spread & water column") return <><AnalyticsCard title="GPS Speed Performance"><Buckets rows={measurementBuckets(data.catches, "gpsSpeed", .5, .1, 15)} /></AnalyticsCard><AnalyticsCard title="Ball Speed Performance"><Buckets rows={measurementBuckets(data.catches, "ballSpeed", .5, .1, 15)} /></AnalyticsCard><AnalyticsCard title="Distance Behind Performance"><Buckets rows={measurementBuckets(data.catches, "lineOut", 25)} /></AnalyticsCard><AnalyticsCard title="Probe Temperature Profile"><SimpleRows rows={probeRows(data.trips)} empty="No probe temperature profiles in this scope" /></AnalyticsCard></>;
  if (name === "Trip patterns") return <><AnalyticsCard title="Location Breakdown"><Ranked rows={data.locations} /></AnalyticsCard><AnalyticsCard title="Method Breakdown"><Ranked rows={data.methods} /></AnalyticsCard><AnalyticsCard title="Person Breakdown"><SimpleRows rows={tripCategoryRows(data.trips, trip => (trip.people || []).map(person => person.name), data)} empty="No angler data in this scope" /></AnalyticsCard><AnalyticsCard title="Month Patterns"><SimpleRows rows={tripCategoryRows(data.trips, trip => [new Date(`${trip.date}T12:00:00`).toLocaleDateString(undefined, { month: "long" })], data)} empty="No dated trips in this scope" /></AnalyticsCard><AnalyticsCard title="Fishing Confidence"><SimpleRows rows={tripCategoryRows(data.trips, trip => [String(trip.intent || "")], data)} empty="No fishing confidence recorded" /></AnalyticsCard><AnalyticsCard title="Trip Rating Breakdown"><SimpleRows rows={tripCategoryRows(data.trips, trip => [ratingName(trip.tripRating)], data)} empty="No trip ratings recorded" /></AnalyticsCard></>;
  return <><AnalyticsCard title="Water Clarity Breakdown"><SimpleRows rows={tripCategoryRows(data.trips, trip => [String(trip.waterClarity || "")], data)} empty="No water clarity recorded" /></AnalyticsCard><AnalyticsCard title="Weather Breakdown"><SimpleRows rows={tripCategoryRows(data.trips, trip => [String(trip.weather || "")], data)} empty="No weather tags recorded" /></AnalyticsCard><AnalyticsCard title="Wind"><SimpleRows rows={tripCategoryRows(data.trips, trip => [String(trip.wind || "")], data)} empty="No wind data recorded" /></AnalyticsCard><AnalyticsCard title="Best Bite Windows"><Bites rows={data.biteWindows} /></AnalyticsCard><AnalyticsCard title="Front Tag"><SimpleRows rows={tripCategoryRows(data.trips, trip => [String(trip.weatherData?.frontTag || "")], data)} empty="No front tags recorded" /></AnalyticsCard><AnalyticsCard title="Moon Phase"><SimpleRows rows={tripCategoryRows(data.trips, trip => [String((trip.weatherData?.sunMoon as Record<string, unknown> | undefined)?.phase || "")], data)} empty="No moon phase data recorded" /></AnalyticsCard></>;
}

function Ranked({ rows, share = false, detailLabel }: { rows: Performance[]; share?: boolean; detailLabel?: string }) { const max = Math.max(1, ...rows.map(row => row.fish)); return rows.length ? <View>{rows.slice(0, 15).map((row, index) => <View key={`${row.name}-${index}`} style={s.rankRow}><View style={s.rankNumber}><Text style={s.rankNumberText}>{index + 1}</Text></View><View style={s.rankBody}><View style={s.rankTop}><Text style={s.rankName} numberOfLines={2}>{row.name}</Text><Text style={s.rankFish}>{row.fish} fish</Text></View><View style={s.rankTrack}><View style={[s.rankFill, { width: `${Math.max(2, row.fish / max * 100)}%` }]} /></View><Text style={s.rowMeta}>{row.trips} trips · {row.fishPerHour === null ? "rate unavailable" : `${row.fishPerHour.toFixed(2)} fish/hr`}{share && row.catchShare !== null ? ` · ${row.catchShare.toFixed(0)}% fish share` : ""}</Text><Text style={s.rowNote}>{detailLabel || `${row.confidence} confidence · ${row.label}`}</Text></View></View>)}</View> : <EmptyState title="No matching data" description="Change filters or add more complete trip records." />; }
function SimpleRows({ rows, empty }: { rows: SimpleRow[]; empty: string }) { const max = Math.max(1, ...rows.map(row => row.fish)); return rows.length ? <View>{rows.slice(0, 15).map(row => <View key={row.name} style={s.simpleRow}><View style={s.simpleTop}><Text style={s.rankName}>{row.name}</Text><Text style={s.rankFish}>{row.fish} fish</Text></View><View style={s.rankTrack}><View style={[s.rankFill, { width: `${Math.max(2, row.fish / max * 100)}%` }]} /></View><Text style={s.rowMeta}>{row.trips} trips{row.detail ? ` · ${row.detail}` : ""}</Text></View>)}</View> : <EmptyState title={empty} />; }
function Buckets({ rows }: { rows: Array<{ label: string; fish: number; trips: number }> }) { return <SimpleRows rows={rows.map(row => ({ name: row.label, fish: row.fish, trips: row.trips }))} empty="Not enough measurements" />; }
function Bites({ rows }: { rows: Array<{ name: string; fish: number; lost: number; trips: number }> }) { return <SimpleRows rows={rows.map(row => ({ name: row.name, fish: row.fish, trips: row.trips, detail: `${row.lost} lost` }))} empty="No catch times in this scope" />; }
function Outcome({ data }: { data: ReturnType<typeof buildAnalytics> }) { const total = data.summary.landed + data.summary.lost; const rows = [{ name: "Landed", value: data.summary.landed, total }, { name: "Released after landing", value: data.summary.released, total: data.summary.landed }, { name: "Kept / harvested", value: data.summary.kept, total: data.summary.landed }, { name: "Lost fish", value: data.summary.lost, total }]; return <View>{rows.map(row => <View key={row.name} style={s.dataRow}><Text style={s.dataName}>{row.name}</Text><Text style={s.dataValue}>{row.value}</Text><Text style={s.dataPercent}>{row.total ? (row.value / row.total * 100).toFixed(1) : "0"}%</Text></View>)}</View>; }
function ReleaseRows({ data }: { data: ReturnType<typeof buildAnalytics> }) { const rows = new Map<string, { landed: number; released: number; trips: Set<string> }>(); data.catches.forEach(item => { const name = String(item.species || "Unknown"), current = rows.get(name) || { landed: 0, released: 0, trips: new Set<string>() }, count = Math.max(1, number(item.quantity)); current.landed += count; if (item.released) current.released += count; current.trips.add(item.trip.id); rows.set(name, current); }); return <SimpleRows rows={[...rows].map(([name, row]) => ({ name, fish: row.landed, trips: row.trips.size, detail: `${row.released} released · ${row.landed ? (row.released / row.landed * 100).toFixed(0) : 0}%` })).sort((a, b) => b.fish - a.fish)} empty="No release data in this scope" />; }
function lostRows(data: ReturnType<typeof buildAnalytics>): SimpleRow[] { const rows = new Map<string, { fish: number; trips: Set<string> }>(); data.lost.forEach(item => { const name = String(item.species || item.possibleSpecies || "Unknown"), current = rows.get(name) || { fish: 0, trips: new Set<string>() }; current.fish += 1; current.trips.add(item.trip.id); rows.set(name, current); }); return [...rows].map(([name, row]) => ({ name, fish: row.fish, trips: row.trips.size })).sort((a, b) => b.fish - a.fish); }
function gearAttributeRows(data: ReturnType<typeof buildAnalytics>, logbook: Logbook, field: "type" | "color"): SimpleRow[] { const lureMap = new Map(logbook.lures.map(lure => [lure.id, String(lure[field] || "")])); const rows = new Map<string, { fish: number; trips: Set<string> }>(); data.catches.forEach(item => { const name = lureMap.get(String(item.lureId || "")); if (!name) return; const current = rows.get(name) || { fish: 0, trips: new Set<string>() }; current.fish += Math.max(1, number(item.quantity)); current.trips.add(item.trip.id); rows.set(name, current); }); return [...rows].map(([name, row]) => ({ name, fish: row.fish, trips: row.trips.size })).sort((a, b) => b.fish - a.fish); }
function tripCategoryRows(trips: Trip[], category: (trip: Trip) => string[], data: ReturnType<typeof buildAnalytics>): SimpleRow[] { const caught = new Map<string, number>(); data.catches.forEach(item => caught.set(item.trip.id, (caught.get(item.trip.id) || 0) + Math.max(1, number(item.quantity)))); const rows = new Map<string, { fish: number; trips: number }>(); trips.forEach(trip => category(trip).filter(Boolean).forEach(name => { const current = rows.get(name) || { fish: 0, trips: 0 }; current.fish += caught.get(trip.id) || 0; current.trips += 1; rows.set(name, current); })); return [...rows].map(([name, row]) => ({ name, ...row })).sort((a, b) => b.fish - a.fish || b.trips - a.trips); }
function probeRows(trips: Trip[]): SimpleRow[] { const rows = new Map<string, { total: number; count: number; trips: Set<string> }>(); trips.forEach(trip => (trip.probeTemperatureProfile || []).forEach(reading => { if (!number(reading.temperature)) return; const name = `${reading.depthFeet} ft`, current = rows.get(name) || { total: 0, count: 0, trips: new Set<string>() }; current.total += number(reading.temperature); current.count += 1; current.trips.add(trip.id); rows.set(name, current); })); return [...rows].map(([name, row]) => ({ name, fish: row.count, trips: row.trips.size, detail: `${(row.total / row.count).toFixed(1)}° average` })); }
function ratingName(value: unknown) { return ["", "Bad", "Mediocre", "Good", "Outstanding"][Math.max(1, Math.min(4, Math.round(number(value))))] || ""; }
function withDatePreset(scope: Scope, preset: DatePreset, logbook: Logbook): Scope { if (preset === "all") return { ...scope, from: undefined, to: undefined }; const latest = Math.max(new Date().getFullYear(), ...logbook.trips.map(trip => Number(trip.date.slice(0, 4))).filter(Number.isFinite)); if (preset === "season") return { ...scope, from: `${latest}-01-01`, to: `${latest}-12-31` }; const to = new Date(), from = new Date(); from.setDate(to.getDate() - Number(preset)); return { ...scope, from: from.toISOString().slice(0, 10), to: to.toISOString().slice(0, 10) }; }

function FilterSheet({ visible, datePreset, setDatePreset, scope, setScope, logbook, onClose }: { visible: boolean; datePreset: DatePreset; setDatePreset: (value: DatePreset) => void; scope: Scope; setScope: (value: Scope) => void; logbook: Logbook; onClose: () => void }) {
  const [more, setMore] = useState(false);
  const primary: Record<string, string[]> = { method: ["All methods", ...logbook.methods], species: ["All species", ...logbook.species], person: ["All people", ...logbook.people.map(item => item.name)], location: ["All locations", ...Array.from(new Set(logbook.trips.map(item => item.location || "").filter(Boolean)))], launch: ["All launches", ...Array.from(new Set(logbook.trips.map(item => item.launch || "").filter(Boolean)))], lure: ["All lures", ...logbook.lures.map(item => item.name)] };
  const secondary: Record<string, string[]> = { flasher: ["All flashers", ...logbook.flashers.map(item => item.name)], waterClarity: ["All clarity", ...logbook.waterClarities], weather: ["All weather", ...logbook.weatherTypes], month: ["All months", ...Array.from({ length: 12 }, (_, index) => new Date(2020, index, 1).toLocaleString(undefined, { month: "long" }))], rating: ["All ratings", "Bad", "Mediocre", "Good", "Outstanding"] };
  const field = ([key, options]: [string, string[]]) => <Pressable accessibilityRole="button" key={key} onPress={() => setScope({ ...scope, [key]: cycle(options, String(scope[key as keyof Scope] || options[0])) })} style={s.filterField}><Text style={s.filterFieldLabel}>{key === "waterClarity" ? "WATER CLARITY" : key.toUpperCase()}</Text><View style={s.filterFieldValueRow}><Text style={s.filterFieldValue} numberOfLines={1}>{String(scope[key as keyof Scope] || options[0])}</Text><Text style={s.filterChevron}>⌄</Text></View></Pressable>;
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={s.modal}><Pressable style={StyleSheet.absoluteFill} onPress={onClose} /><View style={s.sheet}>
    <View style={s.sheetHeader}><View><Text style={s.sheetTitle}>Stats filters</Text><Text style={s.sheetSubtitle}>Match the desktop scope, one tap at a time.</Text></View><Pressable accessibilityLabel="Close filters" onPress={onClose} style={s.closeButton}><Text style={s.closeText}>×</Text></Pressable></View>
    <ScrollView contentContainerStyle={s.sheetScroll} keyboardShouldPersistTaps="handled"><Pressable onPress={() => setDatePreset(cycle(["all", "season", "30", "90"], datePreset) as DatePreset)} style={s.filterField}><Text style={s.filterFieldLabel}>DATE RANGE</Text><View style={s.filterFieldValueRow}><Text style={s.filterFieldValue}>{dateLabel[datePreset]}</Text><Text style={s.filterChevron}>⌄</Text></View></Pressable>{Object.entries(primary).map(field)}<Pressable onPress={() => setMore(value => !value)} style={s.moreFilters}><Text style={s.moreText}>More filters</Text><Text style={s.moreIcon}>{more ? "−" : "+"}</Text></Pressable>{more ? <View style={s.moreBody}>{Object.entries(secondary).map(field)}</View> : null}</ScrollView>
    <View style={s.sheetActions}><SecondaryButton label="Clear" onPress={() => { setScope({}); setDatePreset("all"); }} /><PrimaryButton label="Apply Filters" onPress={onClose} /></View>
  </View></View></Modal>;
}

const s = StyleSheet.create({
  page: { gap: 14, paddingBottom: 28 }, scopeRow: { minHeight: 64, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12, padding: 12, borderWidth: 1, borderColor: tokens.color.line, borderRadius: tokens.radius.md, backgroundColor: tokens.color.panel }, scopeCopy: { flex: 1, gap: 3 }, scopeLabel: { color: tokens.color.muted, fontSize: 9, fontWeight: "900", letterSpacing: .7 }, scopeText: { color: tokens.color.text, fontSize: 13, fontWeight: "800", lineHeight: 18 }, filterRail: { gap: 7 }, filterChip: { borderWidth: 1, borderColor: tokens.color.chipLine, borderRadius: 6, backgroundColor: tokens.color.activeBackground, paddingHorizontal: 10, paddingVertical: 7 }, filterText: { color: tokens.color.greenDark, fontSize: 12, fontWeight: "700" },
  metricGrid: { flexDirection: "row", flexWrap: "wrap", gap: 1, padding: 1, borderRadius: tokens.radius.md, overflow: "hidden", backgroundColor: tokens.color.line }, metricCard: { width: "49.8%", minHeight: 100, flexGrow: 1, justifyContent: "center", gap: 5, padding: 14, backgroundColor: tokens.color.panel }, metricLabel: { color: tokens.color.muted, fontSize: 11, fontWeight: "800" }, metricValue: { color: tokens.color.text, fontSize: 24, lineHeight: 28, fontWeight: "900" }, metricDetail: { color: tokens.color.muted, fontSize: 10, lineHeight: 15 },
  overviewStack: { gap: 12 }, card: { borderWidth: 1, borderColor: tokens.color.line, borderRadius: tokens.radius.md, overflow: "hidden", backgroundColor: tokens.color.panel }, cardHeader: { minHeight: 48, justifyContent: "center", paddingHorizontal: 14, borderBottomWidth: 1, borderBottomColor: tokens.color.line }, cardTitle: { color: tokens.color.text, fontSize: 14, fontWeight: "900" }, cardBody: { minHeight: 32 }, legend: { flexDirection: "row", alignItems: "center", gap: 13, paddingHorizontal: 14, paddingBottom: 13 }, legendItem: { flexDirection: "row", alignItems: "center", gap: 5 }, legendDot: { width: 8, height: 8, borderRadius: 4 }, legendText: { color: tokens.color.muted, fontSize: 10, fontWeight: "700" }, legendRange: { flex: 1, color: tokens.color.muted, fontSize: 9, textAlign: "right" },
  compactRow: { minHeight: 42, flexDirection: "row", alignItems: "center", gap: 8, paddingHorizontal: 12 }, compactName: { width: 90, color: tokens.color.text, fontSize: 11, fontWeight: "800" }, compactTrack: { flex: 1, height: 8, borderRadius: 8, overflow: "hidden", backgroundColor: tokens.color.black }, compactFill: { height: "100%", borderRadius: 8, backgroundColor: tokens.color.green }, compactValue: { width: 25, color: tokens.color.text, fontSize: 11, fontWeight: "900", textAlign: "right" },
  groupStack: { gap: 10 }, groupHeader: { minHeight: 76, flexDirection: "row", alignItems: "center", gap: 12, paddingHorizontal: 14, paddingVertical: 12, borderWidth: 1, borderColor: tokens.color.line, borderRadius: tokens.radius.md, backgroundColor: tokens.color.panel }, pressed: { backgroundColor: tokens.color.hover }, groupCopy: { flex: 1, gap: 5 }, groupTitle: { color: tokens.color.text, fontSize: 16, fontWeight: "900" }, groupDescription: { color: tokens.color.muted, fontSize: 11, lineHeight: 16 }, groupIcon: { width: 28, color: tokens.color.muted, fontSize: 22, fontWeight: "800", textAlign: "center" }, groupBody: { gap: 10, paddingTop: 10 },
  rankRow: { minHeight: 88, flexDirection: "row", alignItems: "flex-start", gap: 10, padding: 12, borderBottomWidth: 1, borderBottomColor: tokens.color.line }, rankNumber: { width: 23, height: 23, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: tokens.color.green, borderRadius: 12 }, rankNumberText: { color: tokens.color.greenDark, fontSize: 10, fontWeight: "900" }, rankBody: { flex: 1, gap: 5 }, rankTop: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 10 }, rankName: { flex: 1, color: tokens.color.text, fontSize: 13, fontWeight: "800", lineHeight: 18 }, rankFish: { color: tokens.color.greenDark, fontSize: 12, fontWeight: "900" }, rankTrack: { height: 4, borderRadius: 4, overflow: "hidden", backgroundColor: tokens.color.line }, rankFill: { height: "100%", borderRadius: 4, backgroundColor: tokens.color.green }, rowMeta: { color: tokens.color.muted, fontSize: 10, lineHeight: 15 }, rowNote: { color: tokens.color.greenDark, fontSize: 10, lineHeight: 15 }, simpleRow: { gap: 6, padding: 12, borderBottomWidth: 1, borderBottomColor: tokens.color.line }, simpleTop: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 10 },
  dataRow: { minHeight: 46, flexDirection: "row", alignItems: "center", gap: 10, paddingHorizontal: 13, borderBottomWidth: 1, borderBottomColor: tokens.color.line }, dataName: { flex: 1, color: tokens.color.text, fontSize: 12, fontWeight: "700" }, dataValue: { width: 42, color: tokens.color.text, fontSize: 13, fontWeight: "900", textAlign: "right" }, dataPercent: { width: 54, color: tokens.color.muted, fontSize: 11, textAlign: "right" },
  modal: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(3,8,13,.76)" }, sheet: { maxHeight: "94%", gap: 13, padding: 18, paddingBottom: 28, borderTopWidth: 1, borderTopColor: tokens.color.line, borderTopLeftRadius: 20, borderTopRightRadius: 20, backgroundColor: tokens.color.panel }, sheetHeader: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 12 }, sheetTitle: { color: tokens.color.text, fontSize: 22, fontWeight: "900" }, sheetSubtitle: { marginTop: 3, color: tokens.color.muted, fontSize: 11 }, closeButton: { width: 36, height: 36, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: tokens.color.line, borderRadius: 8 }, closeText: { color: tokens.color.text, fontSize: 24, lineHeight: 26 }, sheetScroll: { gap: 9 }, filterField: { minHeight: 62, justifyContent: "center", gap: 5, paddingHorizontal: 12, borderWidth: 1, borderColor: tokens.color.line, borderRadius: 7, backgroundColor: tokens.color.field }, filterFieldLabel: { color: tokens.color.muted, fontSize: 9, fontWeight: "900", letterSpacing: .6 }, filterFieldValueRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 }, filterFieldValue: { flex: 1, color: tokens.color.text, fontSize: 13, fontWeight: "800" }, filterChevron: { color: tokens.color.muted, fontSize: 18 }, moreFilters: { minHeight: 48, flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 12, borderWidth: 1, borderColor: tokens.color.line, borderRadius: 7, backgroundColor: tokens.color.panelSoft }, moreText: { color: tokens.color.text, fontSize: 12, fontWeight: "800" }, moreIcon: { color: tokens.color.muted, fontSize: 18, fontWeight: "800" }, moreBody: { gap: 9 }, sheetActions: { flexDirection: "row", justifyContent: "flex-end", gap: 9 },
});
