import type { Catch, Logbook, SetupLine, Trip } from "../types";
import { fishCount, firstNumber, numericValue, setupMinutes, tripHours } from "./duration";
import { gearName, resolveCatch, type ResolvedCatch } from "./setup-resolution";

export type Scope = { method?: string; species?: string; location?: string; launch?: string; lure?: string; flasher?: string; person?: string; weather?: string; waterClarity?: string; month?: string; rating?: string; from?: string; to?: string; includeLost?: boolean };
export type RecordWithTrip = ResolvedCatch;
export type Performance = { name: string; fish: number; lost: number; strikes: number; hours: number | null; trips: number; fishPerHour: number | null; strikesPerHour: number | null; landingPercentage: number | null; fishPerTrip: number; usageShare: number | null; catchShare: number | null; efficiencyIndex: number | null; overperformance: number | null; confidence: "Low" | "Medium" | "High"; label: string; missingTime: boolean };
export type AnalyticsReport = { trips: Trip[]; catches: RecordWithTrip[]; lost: RecordWithTrip[]; gear: Array<SetupLine & { trip: Trip }>; summary: { trips: number; landed: number; lost: number; released: number; kept: number; hours: number; fishPerHour: number; landingRate: number | null }; species: Performance[]; locations: Performance[]; methods: Performance[]; lures: Performance[]; flashers: Performance[]; presentations: Performance[]; directions: Performance[]; sides: Performance[]; combos: Performance[]; biteWindows: Array<{ name: string; fish: number; lost: number; trips: number }>; quality: string[] };

const all = (value?: string) => !value || /^All /i.test(value);
const monthName = (date?: string) => date ? new Date(`${date}T12:00:00`).toLocaleDateString(undefined, { month: "long" }) : "";
const ratingName = (value: unknown) => ["", "Bad", "Mediocre", "Good", "Outstanding"][Math.max(1, Math.min(4, numericValue(value, 1)))] || "";
const recordPerson = (logbook: Logbook, trip: Trip, record: Catch) => { const id = String(record.personId || ""); return String(logbook.people.find(person => String(person.id || "") === id)?.name || (trip.people as Array<Record<string, unknown>> | undefined)?.find(person => String(person.id || "") === id)?.name || ""); };

function matchTrip(logbook: Logbook, trip: Trip, scope: Scope): boolean {
  if (scope.from && trip.date < scope.from || scope.to && trip.date > scope.to) return false;
  return (all(scope.method) || trip.method === scope.method) && (all(scope.location) || trip.location === scope.location) && (all(scope.launch) || trip.launch === scope.launch) && (all(scope.weather) || trip.weather === scope.weather) && (all(scope.waterClarity) || trip.waterClarity === scope.waterClarity) && (all(scope.month) || monthName(trip.date) === scope.month) && (all(scope.rating) || ratingName(trip.tripRating) === scope.rating) && (all(scope.species) || [...trip.catches, ...trip.lostFish].some(item => item.species === scope.species || item.possibleSpecies === scope.species)) && (all(scope.person) || [...trip.catches, ...trip.lostFish].some(item => recordPerson(logbook, trip, item) === scope.person));
}

function matchRecord(logbook: Logbook, record: RecordWithTrip, scope: Scope): boolean {
  return (all(scope.species) || record.species === scope.species || record.possibleSpecies === scope.species) && (all(scope.person) || recordPerson(logbook, record.trip, record) === scope.person) && (all(scope.lure) || gearName(logbook, "lure", String(record.lureId || "")) === scope.lure) && (all(scope.flasher) || gearName(logbook, "flasher", String(record.flasherId || "")) === scope.flasher);
}

export function confidence(hours = 0, trips = 0): "Low" | "Medium" | "High" { return trips >= 6 && hours >= 15 ? "High" : trips >= 3 && hours >= 5 ? "Medium" : "Low"; }
export const safeDivide = (left: number, right: number | null | undefined): number | null => Number.isFinite(left) && Number.isFinite(right) && (right || 0) > 0 ? left / Number(right) : null;

export function performanceMetrics(input: { landed?: number; lost?: number; missed?: number; hours?: number | null; trips?: number; totalHours?: number | null; totalLanded?: number }): Omit<Performance, "name" | "label" | "missingTime"> {
  const landed = input.landed || 0, lost = input.lost || 0, missed = input.missed || 0, hours = input.hours && input.hours > 0 ? input.hours : null, trips = input.trips || 0, strikes = landed + lost + missed;
  const usageShare = safeDivide(hours || 0, input.totalHours), catchShare = safeDivide(landed, input.totalLanded), efficiencyIndex = usageShare && catchShare !== null ? catchShare / usageShare : null;
  return { fish: landed, lost, strikes, hours, trips, fishPerHour: safeDivide(landed, hours), strikesPerHour: safeDivide(strikes, hours), landingPercentage: safeDivide(landed, landed + lost), fishPerTrip: safeDivide(landed, trips) || 0, usageShare, catchShare, efficiencyIndex, overperformance: usageShare !== null && catchShare !== null ? catchShare - usageShare : null, confidence: confidence(hours || 0, trips) };
}

function label(metrics: Omit<Performance, "name" | "label" | "missingTime">, averageRate: number): string {
  if (!metrics.hours && metrics.fish > 0) return "Missing time data";
  if (metrics.strikes >= 3 && metrics.landingPercentage !== null && metrics.landingPercentage < .5) return "High strikes, low landing";
  if (metrics.confidence === "Low" && (metrics.fishPerHour || 0) > averageRate) return "Promising, needs more data";
  if (metrics.confidence === "Low") return "Insufficient data";
  if ((metrics.efficiencyIndex || 0) >= 1.5) return "High efficiency";
  if ((metrics.usageShare || 0) >= .15 && (metrics.efficiencyIndex || 0) < .75) return "Overused, low return";
  if (metrics.fish >= 2 && (metrics.fishPerHour || 0) >= averageRate) return "Consistent producer";
  return metrics.fish ? "Watch list" : "No catches yet";
}

function groupedPerformance(rows: Array<{ name: string; fish: number; lost?: number; minutes?: number; hours?: number; tripId: string; hasTime?: boolean }>, totalHours: number, totalFish: number): Performance[] {
  const groups = new Map<string, { fish: number; lost: number; minutes: number; hours: number; time: boolean; trips: Set<string> }>();
  rows.forEach(row => { if (!row.name) return; const value = groups.get(row.name) || { fish: 0, lost: 0, minutes: 0, hours: 0, time: false, trips: new Set<string>() }; value.fish += row.fish; value.lost += row.lost || 0; value.minutes += row.minutes || 0; value.hours += row.hours || 0; value.time ||= Boolean(row.hasTime || row.minutes || row.hours); value.trips.add(row.tripId); groups.set(row.name, value); });
  const average = totalHours ? totalFish / totalHours : 0;
  return [...groups.entries()].map(([name, value]) => { const hours = value.hours || value.minutes / 60; const metrics = performanceMetrics({ landed: value.fish, lost: value.lost, hours: value.time ? hours : null, trips: value.trips.size, totalHours, totalLanded: totalFish }); return { name, ...metrics, usageShare: metrics.usageShare === null ? null : metrics.usageShare * 100, catchShare: metrics.catchShare === null ? null : metrics.catchShare * 100, overperformance: metrics.overperformance === null ? null : metrics.overperformance * 100, missingTime: value.fish > 0 && !metrics.hours, label: label(metrics, average) }; }).sort((a, b) => (b.fishPerHour || -1) - (a.fishPerHour || -1) || b.fish - a.fish || a.name.localeCompare(b.name));
}

function biteWindow(record: RecordWithTrip): string { const hour = Number(String(record.time || "").split(":")[0]); if (!Number.isFinite(hour)) return "No time"; return hour < 5 || hour >= 21 ? "Night" : hour < 10 ? "Morning" : hour < 14 ? "Midday" : hour < 18 ? "Afternoon" : "Evening"; }

/** Desktop-compatible analytical dataset, purposely presentation-neutral for native charts and lists. */
export function buildAnalytics(logbook: Logbook, scope: Scope = {}): AnalyticsReport {
  const trips = logbook.trips.filter(trip => matchTrip(logbook, trip, scope));
  const catches = trips.flatMap(trip => trip.catches.map(item => resolveCatch(trip, item))).filter(record => matchRecord(logbook, record, scope));
  const lost = trips.flatMap(trip => trip.lostFish.map(item => resolveCatch(trip, item, true))).filter(record => matchRecord(logbook, record, scope));
  const gear = trips.flatMap(trip => trip.gearUsed.map(line => ({ ...line, trip }))).filter(line => (all(scope.lure) || gearName(logbook, "lure", line.lureId) === scope.lure) && (all(scope.flasher) || gearName(logbook, "flasher", line.flasherId) === scope.flasher));
  const landed = catches.reduce((sum, item) => sum + fishCount(item), 0), lostCount = lost.length, hours = trips.reduce((sum, trip) => sum + tripHours(trip), 0), released = catches.filter(item => item.released).reduce((sum, item) => sum + fishCount(item), 0);
  const tripRows = (key: (trip: Trip) => string) => trips.map(trip => ({ name: key(trip), fish: catches.filter(item => item.trip.id === trip.id).reduce((sum, item) => sum + fishCount(item), 0), lost: lost.filter(item => item.trip.id === trip.id).length, hours: tripHours(trip), hasTime: true, tripId: trip.id }));
  const effort = (kind: "lure" | "flasher" | "presentation" | "direction" | "side") => gear.map(line => ({ name: kind === "lure" ? gearName(logbook, "lure", line.lureId) : kind === "flasher" ? gearName(logbook, "flasher", line.flasherId) : String((line as Record<string, unknown>)[kind] || ""), fish: catches.filter(item => item.setupLineId === line.id).reduce((sum, item) => sum + fishCount(item), 0), lost: lost.filter(item => item.setupLineId === line.id).length, minutes: setupMinutes(line), hasTime: true, tripId: line.trip.id }));
  const catchGroups = (key: (record: RecordWithTrip) => string) => catches.map(record => ({ name: key(record), fish: fishCount(record), tripId: record.trip.id }));
  const bites = new Map<string, { fish: number; lost: number; trips: Set<string> }>();
  [...catches, ...lost].forEach(record => { const name = biteWindow(record); const entry = bites.get(name) || { fish: 0, lost: 0, trips: new Set<string>() }; if (record.lost) entry.lost += 1; else entry.fish += fishCount(record); entry.trips.add(record.trip.id); bites.set(name, entry); });
  return { trips, catches, lost, gear, summary: { trips: trips.length, landed, lost: lostCount, released, kept: Math.max(0, landed - released), hours, fishPerHour: hours ? landed / hours : 0, landingRate: safeDivide(landed, landed + lostCount) }, species: groupedPerformance(catchGroups(record => String(record.species || "Unknown")), hours, landed), locations: groupedPerformance(tripRows(trip => String(trip.location || "Unknown")), hours, landed), methods: groupedPerformance(tripRows(trip => String(trip.method || "Unknown")), hours, landed), lures: groupedPerformance(effort("lure"), gear.filter(line => line.lureId).reduce((sum, line) => sum + setupMinutes(line), 0) / 60, landed), flashers: groupedPerformance(effort("flasher"), gear.filter(line => line.flasherId).reduce((sum, line) => sum + setupMinutes(line), 0) / 60, landed), presentations: groupedPerformance(effort("presentation"), gear.reduce((sum, line) => sum + setupMinutes(line), 0) / 60, landed), directions: groupedPerformance(effort("direction"), gear.reduce((sum, line) => sum + setupMinutes(line), 0) / 60, landed), sides: groupedPerformance(effort("side"), gear.reduce((sum, line) => sum + setupMinutes(line), 0) / 60, landed), combos: groupedPerformance(gear.filter(line => line.lureId && line.flasherId).map(line => ({ name: [gearName(logbook, "lure", line.lureId), gearName(logbook, "flasher", line.flasherId)].filter(Boolean).join(" + "), fish: catches.filter(item => item.setupLineId === line.id).reduce((sum, item) => sum + fishCount(item), 0), lost: lost.filter(item => item.setupLineId === line.id).length, minutes: Math.min(numericValue(line.lureMinutes), numericValue(line.flasherMinutes)) || setupMinutes(line), hasTime: true, tripId: line.trip.id })), gear.reduce((sum, line) => sum + setupMinutes(line), 0) / 60, landed), biteWindows: [...bites.entries()].map(([name, value]) => ({ name, fish: value.fish, lost: value.lost, trips: value.trips.size })).sort((a, b) => b.fish + b.lost - (a.fish + a.lost)), quality: dataQuality(logbook, trips) };
}

export function dataQuality(logbook: Logbook, trips = logbook.trips): string[] { const errors: string[] = []; trips.forEach(trip => { if (!trip.location && !trip.locationId) errors.push(`${trip.title}: missing location`); if (!trip.method) errors.push(`${trip.title}: missing method`); if (!tripHours(trip)) errors.push(`${trip.title}: missing trip duration`); if (!trip.coordinates && !trip.catches.some(item => item.coordinates || item.manualCoordinates)) errors.push(`${trip.title}: missing GPS`); if (!trip.weather && !trip.waterTemp && !trip.waterClarity && !trip.wind) errors.push(`${trip.title}: missing conditions`); if (tripHours(trip) > 0 && trip.gearUsed.length && !trip.gearUsed.some(line => setupMinutes(line) > 0)) errors.push(`${trip.title}: setup rows have no timing`); trip.catches.forEach(item => { if (!item.species) errors.push(`${trip.title}: catch ${item.id} missing species`); if (!item.time || item.timeUnknown) errors.push(`${trip.title}: catch ${item.id} missing catch time`); if (trip.method === "Trolling" && !item.setupLineId) errors.push(`${trip.title}: catch ${item.id} has no setup line`); if (trip.method === "Trolling" && firstNumber(item.fowCaught ?? item.waterDepth ?? item.depthDown) === null) errors.push(`${trip.title}: catch ${item.id} missing depth`); if (item.setupLineId && !trip.gearUsed.some(line => line.id === item.setupLineId)) errors.push(`${trip.title}: catch ${item.id} references a missing setup line`); }); }); return errors; }

export function measurementBuckets(records: RecordWithTrip[], field: string, step: number, min = -Infinity, max = Infinity): Array<{ label: string; fish: number; trips: number; average: number }> { const groups = new Map<string, { values: number[]; fish: number; trips: Set<string> }>(); records.forEach(record => { const value = firstNumber(record[field]); if (value === null || value < min || value > max) return; const start = Math.floor(value / step) * step, label = `${start}–${start + step}`; const entry = groups.get(label) || { values: [], fish: 0, trips: new Set<string>() }; entry.values.push(value); entry.fish += fishCount(record); entry.trips.add(record.trip.id); groups.set(label, entry); }); return [...groups.entries()].map(([label, item]) => ({ label, fish: item.fish, trips: item.trips.size, average: item.values.reduce((sum, value) => sum + value, 0) / item.values.length })).sort((a, b) => a.average - b.average); }
