"""Render standalone.html, the direct-file (file://) fallback shell.

Run after ``npm run build``; the page loads the same bundle from static/dist.
standalone.html is generated output and is not committed.
"""

from __future__ import annotations

import sys
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, select_autoescape


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from backend.frontend_assets import asset_url, frontend_is_built  # noqa: E402

TEMPLATES = ROOT / "templates"
OUTPUT = ROOT / "standalone.html"
GENERATED_BANNER = "<!-- Generated by scripts/build-standalone.py; edit templates/ instead. -->\n"


def rendered_document() -> str:
    environment = Environment(
        loader=FileSystemLoader(TEMPLATES),
        autoescape=select_autoescape(enabled_extensions=("html",)),
        keep_trailing_newline=True,
    )
    environment.globals["asset_url"] = asset_url
    document = environment.get_template("index.html").render(initial_theme="")
    return document.replace("<!doctype html>\n", f"<!doctype html>\n{GENERATED_BANNER}", 1)


def main() -> int:
    if not frontend_is_built():
        print("static/dist is missing; run `npm run build` first.", file=sys.stderr)
        return 1
    OUTPUT.write_text(rendered_document(), encoding="utf-8", newline="\n")
    print(f"Wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
