from __future__ import annotations

import argparse
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, select_autoescape


ROOT = Path(__file__).resolve().parents[1]
TEMPLATES = ROOT / "templates"
OUTPUT = ROOT / "standalone.html"
GENERATED_BANNER = "<!-- Generated by scripts/build-standalone.py; edit templates/ instead. -->\n"


def rendered_document() -> str:
    environment = Environment(
        loader=FileSystemLoader(TEMPLATES),
        autoescape=select_autoescape(enabled_extensions=("html",)),
        keep_trailing_newline=True,
    )
    document = environment.get_template("index.html").render(initial_theme="")
    return document.replace("<!doctype html>\n", f"<!doctype html>\n{GENERATED_BANNER}", 1)


def main() -> int:
    parser = argparse.ArgumentParser(description="Build the direct-file Fishing Logbook fallback.")
    parser.add_argument("--check", action="store_true", help="Fail when standalone.html is out of date.")
    args = parser.parse_args()
    expected = rendered_document()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            print("standalone.html is out of date; run: py scripts/build-standalone.py")
            return 1
        print("standalone.html is up to date")
        return 0
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"Wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
