import { useMemo, useState } from "react";
import { Alert, Pressable, StyleSheet, Text, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { DangerButton, EmptyState, Field, MetricStrip, Panel, PrimaryButton, Screen, SecondaryButton, TopBar } from "../../components/ui";
import { dataQuality, mediaReferences } from "../../domain/analytics";
import { id, usableCoordinates } from "../../domain/logbook";
import { useLogbook } from "../../state/logbook-context";
import { exportLogbook, importLogbook } from "../../storage/archive";
import { fetchAstronomy, fetchDepth, fetchMarine, fetchWeather } from "../../services/providers";
import { currentCoordinates } from "../../services/location";
import { tokens } from "../../theme/tokens";

import { ReferenceLibrary } from "./ReferenceLibrary";

const fieldKeys=["riggings","structureOptions","species","methods","lureTypes","flasherTypes","waterClarities","weatherTypes","reelStyles","rodTypes","lineTypes","lureBladeTypes","lureSpoonSizes","trollingDirections"] as const;
const units:Record<string,string[]>={depth:["ft","m"],distance:["km","mi"],speed:["mph","kph","kn"],windSpeed:["kph","mph","kn"],pressure:["hPa","kPa","inHg","mmHg"],airTemperature:["C","F"],waterTemperature:["F","C"],precipitation:["mm","in"],waveHeight:["ft","m"],fishLength:["in","cm"],fishWeight:["lb","kg"]};
export function SettingsScreen(){
  const {section="general"}=useLocalSearchParams<{section:string}>();const router=useRouter();const {logbook,update}=useLogbook();
  const close=()=>router.canGoBack()?router.back():router.replace("/(tabs)/more");
  return <Screen><TopBar title={title(section)} subtitle="Local app preferences and ownership" actions={<SecondaryButton label="Back" compact onPress={close}/>}/>
    {section==="expeditions"||section==="spots"?<ReferenceLibrary kind={section}/>:section==="general"?<General logbook={logbook} update={update}/>:section==="fields"?<Fields logbook={logbook} update={update}/>:section==="locations"?<Locations logbook={logbook} update={update}/>:section==="data"?<DataTools logbook={logbook} update={update}/>:section==="environment"?<Environment logbook={logbook} update={update}/>:<Diagnostics logbook={logbook}/>}
  </Screen>
}
const title=(section:string)=>({expeditions:"Expeditions",spots:"Fishing Spots",general:"Settings & Units",fields:"Predefined Fields",locations:"Waterbodies & Launches",data:"Import, Export & Backups",environment:"Weather, Marine & Depth",diagnostics:"Storage & Diagnostics"}[section]||"Settings");
function General({logbook,update}:{logbook:any;update:(v:any)=>Promise<void>}){const settings=logbook.settings||{},current=settings.units||{};const set=(key:string,value:string)=>update({...logbook,settings:{...settings,units:{...current,[key]:value}}});return <View style={s.stack}><Panel title="Time format"><View style={s.actions}>{["12","24"].map(v=><SecondaryButton key={v} label={`${v}-hour`} onPress={()=>update({...logbook,settings:{...settings,timeFormat:v}})} style={settings.timeFormat===v?s.selected:undefined}/>)}</View></Panel><Panel title="Display units" subtitle="Tap a row to cycle through compatible units.">{Object.entries(units).map(([key,values])=><Pressable key={key} style={s.row} onPress={()=>set(key,values[(values.indexOf(current[key])+1)%values.length])}><Text style={s.rowTitle}>{key}</Text><Text style={s.value}>{current[key]} ›</Text></Pressable>)}</Panel><Panel title="Wave chop ranges">{(settings.chopRanges||[]).map((item:any)=><View key={item.id} style={s.row}><Text style={s.rowTitle}>{item.label}</Text><Text style={s.value}>{item.maxFeet==null?"Open ended":`≤ ${item.maxFeet} ft`}</Text></View>)}</Panel></View>}
function Fields({logbook,update}:{logbook:any;update:(v:any)=>Promise<void>}){const [kind,setKind]=useState<typeof fieldKeys[number]>("species"),[value,setValue]=useState("");const values=logbook[kind] as string[];const add=()=>{const clean=value.trim();if(clean&&!values.some(v=>v.toLowerCase()===clean.toLowerCase()))update({...logbook,[kind]:[...values,clean]});setValue("")};return <View style={s.stack}><View style={s.chips}>{fieldKeys.map(k=><Pressable key={k} onPress={()=>setKind(k)} style={[s.chip,k===kind&&s.chipActive]}><Text style={[s.chipText,k===kind&&s.chipTextActive]}>{k}</Text></Pressable>)}</View><Panel title={kind}><View style={s.actions}><Field label="New value" value={value} onChangeText={setValue} containerStyle={{flex:1}}/><PrimaryButton label="Add" onPress={add}/></View>{values.map(item=><View key={item} style={s.row}><Text style={s.rowTitle}>{item}</Text><DangerButton label="Delete" compact onPress={()=>update({...logbook,[kind]:values.filter(v=>v!==item)})}/></View>)}</Panel></View>}
function Locations({logbook,update}:{logbook:any;update:(v:any)=>Promise<void>}){
  const blank={name:"",latitude:"",longitude:"",launchName:"",launchLatitude:"",launchLongitude:""};
  const [draft,setDraft]=useState(blank),[editingId,setEditingId]=useState(""),[busy,setBusy]=useState(false);
  const coordinates=(latitude:string,longitude:string)=>{const lat=Number(latitude),lon=Number(longitude);return Number.isFinite(lat)&&Number.isFinite(lon)&&latitude.trim()&&longitude.trim()?{latitude:lat,longitude:lon}:undefined};
  const edit=(location:any)=>{setEditingId(location.id);setDraft({...blank,name:location.name,latitude:String(location.coordinates?.latitude??""),longitude:String(location.coordinates?.longitude??"")})};
  const cancel=()=>{setEditingId("");setDraft(blank)};
  const save=async()=>{const name=draft.name.trim();if(!name)return;const next=editingId?logbook.locations.map((location:any)=>location.id===editingId?{...location,name,coordinates:coordinates(draft.latitude,draft.longitude)}:location):[...logbook.locations,{id:id(),name,coordinates:coordinates(draft.latitude,draft.longitude),launches:[]}];await update({...logbook,locations:next});cancel()};
  const useGps=async(prefix:"location"|"launch")=>{setBusy(true);try{const fix=await currentCoordinates();setDraft(current=>prefix==="location"?{...current,latitude:String(fix.latitude),longitude:String(fix.longitude)}:{...current,launchLatitude:String(fix.latitude),launchLongitude:String(fix.longitude)})}catch(error){Alert.alert("Location unavailable",error instanceof Error?error.message:String(error))}finally{setBusy(false)}};
  const addLaunch=async(locationId:string)=>{const name=draft.launchName.trim();if(!name)return;await update({...logbook,locations:logbook.locations.map((location:any)=>location.id===locationId?{...location,launches:[...(location.launches||[]),{id:id(),name,coordinates:coordinates(draft.launchLatitude,draft.launchLongitude)}]}:location)});setDraft(current=>({...current,launchName:"",launchLatitude:"",launchLongitude:""}))};
  const removeLaunch=(location:any,launch:any)=>{const used=logbook.trips.filter((trip:any)=>trip.launchId===launch.id||(!trip.launchId&&trip.location===location.name&&trip.launch===launch.name)).length;if(used){Alert.alert("Launch is in use",`${used} trip${used===1?"":"s"} reference this launch. Rename it instead so historical links remain intact.`);return}Alert.alert("Delete launch?",launch.name,[{text:"Cancel",style:"cancel"},{text:"Delete",style:"destructive",onPress:()=>update({...logbook,locations:logbook.locations.map((item:any)=>item.id===location.id?{...item,launches:item.launches.filter((entry:any)=>entry.id!==launch.id)}:item)})}])};
  const removeLocation=(location:any)=>{const used=logbook.trips.filter((trip:any)=>trip.locationId===location.id||(!trip.locationId&&trip.location===location.name)).length;if(used){Alert.alert("Waterbody is in use",`${used} trip${used===1?"":"s"} reference this waterbody. Rename it instead so historical links remain intact.`);return}Alert.alert("Delete waterbody?",location.name,[{text:"Cancel",style:"cancel"},{text:"Delete",style:"destructive",onPress:()=>update({...logbook,locations:logbook.locations.filter((item:any)=>item.id!==location.id)})}])};
  return <View style={s.stack}><Panel title={editingId?"Edit waterbody":"Add waterbody"} subtitle="Coordinates power maps, live-trip defaults, weather, marine, and depth lookups."><Field label="Name" value={draft.name} onChangeText={name=>setDraft(current=>({...current,name}))}/><View style={s.coordRow}><Field label="Latitude" value={draft.latitude} onChangeText={latitude=>setDraft(current=>({...current,latitude}))} keyboardType="decimal-pad" containerStyle={s.coordField}/><Field label="Longitude" value={draft.longitude} onChangeText={longitude=>setDraft(current=>({...current,longitude}))} keyboardType="decimal-pad" containerStyle={s.coordField}/></View><View style={s.actions}><SecondaryButton label="Use Current GPS" compact loading={busy} onPress={()=>useGps("location")}/><PrimaryButton label={editingId?"Save Waterbody":"Add Waterbody"} compact onPress={save}/>{editingId?<SecondaryButton label="Cancel" compact onPress={cancel}/>:null}</View></Panel>{logbook.locations.map((location:any)=><Panel key={location.id} title={location.name} subtitle={usableCoordinates(location.coordinates)?`${Number(location.coordinates.latitude).toFixed(5)}, ${Number(location.coordinates.longitude).toFixed(5)}`:"Coordinates not set"}><View style={s.actions}><SecondaryButton label="Edit" compact onPress={()=>edit(location)}/><DangerButton label="Delete" compact onPress={()=>removeLocation(location)}/></View>{(location.launches||[]).map((launch:any)=><View key={launch.id} style={s.launchRow}><View style={s.grow}><Text style={s.rowTitle}>{launch.name}</Text><Text style={s.launchMeta}>{usableCoordinates(launch.coordinates)?`${Number(launch.coordinates.latitude).toFixed(5)}, ${Number(launch.coordinates.longitude).toFixed(5)}`:"No coordinates"}</Text></View><DangerButton label="Delete" compact onPress={()=>removeLaunch(location,launch)}/></View>)}<View style={s.launchEditor}><Text style={s.editorTitle}>ADD LAUNCH / AREA</Text><Field label="Name" value={draft.launchName} onChangeText={launchName=>setDraft(current=>({...current,launchName}))}/><View style={s.coordRow}><Field label="Latitude" value={draft.launchLatitude} onChangeText={launchLatitude=>setDraft(current=>({...current,launchLatitude}))} keyboardType="decimal-pad" containerStyle={s.coordField}/><Field label="Longitude" value={draft.launchLongitude} onChangeText={launchLongitude=>setDraft(current=>({...current,launchLongitude}))} keyboardType="decimal-pad" containerStyle={s.coordField}/></View><View style={s.actions}><SecondaryButton label="Use Current GPS" compact loading={busy} onPress={()=>useGps("launch")}/><PrimaryButton label="Add Launch" compact onPress={()=>addLaunch(location.id)}/></View></View></Panel>)}</View>}
function DataTools({logbook,update}:{logbook:any;update:(v:any)=>Promise<void>}){const [busy,setBusy]=useState(false);const run=async(task:()=>Promise<unknown>)=>{setBusy(true);try{await task()}catch(error){Alert.alert("Data operation failed",error instanceof Error?error.message:String(error))}finally{setBusy(false)}};return <View style={s.stack}><Panel title="Desktop-compatible archive"><Text style={s.help}>Export creates a ZIP with manifest.json, logbook.json, and all local originals. Import accepts desktop JSON or Fishing Logbook ZIP archives.</Text><View style={s.actions}><PrimaryButton label="Export ZIP" loading={busy} onPress={()=>run(()=>exportLogbook(logbook))}/><SecondaryButton label="Import" disabled={busy} onPress={()=>run(async()=>{const incoming=await importLogbook();if(incoming)await update(incoming)})}/></View></Panel></View>}
function Environment({logbook,update}:{logbook:any;update:(v:any)=>Promise<void>}){const source=[...logbook.trips].reverse().find((t:any)=>usableCoordinates(t.coordinates));const [busy,setBusy]=useState(false),[status,setStatus]=useState("");const refresh=async()=>{const c=source&&usableCoordinates(source.coordinates);if(!source||!c)return;setBusy(true);const [weather,marine,astronomy,depth]=await Promise.allSettled([fetchWeather(c.latitude,c.longitude),fetchMarine(c.latitude,c.longitude),fetchAstronomy(c.latitude,c.longitude,source.date),fetchDepth(c.latitude,c.longitude)]);const snapshot={source:"mobile-direct",fetchedAt:new Date().toISOString(),weather:weather.status==="fulfilled"?weather.value:{error:String(weather.reason)},marine:marine.status==="fulfilled"?marine.value:{error:String(marine.reason)},sunMoon:astronomy.status==="fulfilled"?astronomy.value:{error:String(astronomy.reason)},depth:depth.status==="fulfilled"?depth.value:{error:String(depth.reason)}};await update({...logbook,trips:logbook.trips.map((t:any)=>t.id===source.id?{...t,weatherData:snapshot}:t)});setStatus("Environmental snapshot saved locally.");setBusy(false)};return <View style={s.stack}>{source?<Panel title={source.title} subtitle={`${source.coordinates.latitude}, ${source.coordinates.longitude}`}><PrimaryButton label="Refresh Environmental Data" loading={busy} onPress={refresh}/>{status?<Text style={s.success}>{status}</Text>:null}{source.weatherData?<Text style={s.help}>Cached snapshot: {String(source.weatherData.fetchedAt||"available")}</Text>:null}</Panel>:<EmptyState title="No geotagged trip" description="Save trip coordinates before requesting weather, marine, astronomy, or depth data."/>}</View>}
function Diagnostics({logbook}:{logbook:any}){const issues=useMemo(()=>dataQuality(logbook),[logbook]),media=useMemo(()=>mediaReferences(logbook),[logbook]);return <View style={s.stack}><MetricStrip metrics={[{label:"Issues",value:issues.length},{label:"Trips",value:logbook.trips.length},{label:"Media refs",value:media.length}]}/><Panel title="Data quality">{issues.length?issues.map((issue:string,i:number)=><View key={i} style={s.issue}><Text style={s.issueText}>{issue}</Text></View>):<EmptyState title="No known data-quality issues"/>}</Panel><Panel title="Local-only privacy"><Text style={s.help}>Records, media, coordinates, and provider snapshots stay in the app sandbox unless you explicitly export or share them.</Text></Panel></View>}
const s=StyleSheet.create({stack:{gap:16},actions:{flexDirection:"row",alignItems:"flex-end",flexWrap:"wrap",gap:9},selected:{backgroundColor:tokens.color.activeBackground,borderColor:tokens.color.chipLine},row:{minHeight:50,flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:10,borderBottomWidth:1,borderColor:tokens.color.line},rowTitle:{flex:1,color:tokens.color.text,fontWeight:"700"},value:{color:tokens.color.greenDark,fontWeight:"800"},chips:{flexDirection:"row",flexWrap:"wrap",gap:7},chip:{paddingVertical:7,paddingHorizontal:10,borderWidth:1,borderColor:tokens.color.line,borderRadius:999,backgroundColor:tokens.color.field},chipActive:{backgroundColor:tokens.color.activeBackground,borderColor:tokens.color.chipLine},chipText:{color:tokens.color.muted,fontSize:11,fontWeight:"700"},chipTextActive:{color:tokens.color.activeText},help:{color:tokens.color.muted,lineHeight:20},success:{color:tokens.color.activeText,fontWeight:"700"},issue:{padding:12,borderLeftWidth:3,borderLeftColor:tokens.color.amber,backgroundColor:tokens.color.panelSoft},issueText:{color:tokens.color.text},coordRow:{flexDirection:"row",gap:9},coordField:{flex:1},launchRow:{minHeight:58,flexDirection:"row",alignItems:"center",gap:10,borderBottomWidth:1,borderBottomColor:tokens.color.line},grow:{flex:1},launchMeta:{color:tokens.color.muted,fontSize:11,marginTop:3},launchEditor:{gap:10,paddingTop:14},editorTitle:{color:tokens.color.muted,fontSize:10,fontWeight:"900",letterSpacing:.6}});
