import { useMemo, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { EmptyState, MetricStrip, PrimaryButton, Screen, SecondaryButton, TopBar } from "../../components/ui";
import type { Coordinates, Trip } from "../../domain/types";
import { currentCoordinates } from "../../services/location";
import { useLogbook } from "../../state/logbook-context";
import { tokens } from "../../theme/tokens";
import { MapCanvas, type MapPoint } from "./MapCanvas";

type PointKind = "Trip" | "Catch" | "Lost fish" | "Photo" | "Live event";
type Point = MapPoint & { kind: PointKind; tripId: string; species?: string; waterbody?: string; time?: string };
const kinds: Array<"All records" | PointKind> = ["All records", "Trip", "Catch", "Lost fish", "Photo", "Live event"];
const cycle = (values: string[], value: string) => values[(values.indexOf(value) + 1) % values.length];
const valid = (coordinates?: Coordinates | null): coordinates is Coordinates => Boolean(coordinates && Number.isFinite(coordinates.latitude) && Number.isFinite(coordinates.longitude));

function pointsForTrip(trip: Trip): Point[] {
  const points: Point[] = [];
  const add = (id: string, kind: PointKind, coordinates: Coordinates | null | undefined, title: string, subtitle?: string, species?: string, time?: string) => {
    if (valid(coordinates)) points.push({ id, kind, tripId: trip.id, latitude: coordinates.latitude, longitude: coordinates.longitude, title, subtitle, species, waterbody: trip.location, time });
  };
  add(`trip-${trip.id}`, "Trip", trip.coordinates, trip.title, [trip.date, trip.location, trip.launch].filter(Boolean).join(" · "));
  trip.catches.forEach(fish => add(`catch-${fish.id}`, "Catch", fish.coordinates || fish.manualCoordinates || fish.lockedLocationCoordinates, `${fish.species || "Fish"} landed`, [trip.location, fish.time, fish.lureName].filter(Boolean).join(" · "), fish.species, fish.time));
  trip.lostFish.forEach(fish => add(`lost-${fish.id}`, "Lost fish", fish.coordinates || fish.manualCoordinates || fish.lockedLocationCoordinates, `${fish.possibleSpecies || "Fish"} lost`, [trip.location, fish.time].filter(Boolean).join(" · "), fish.possibleSpecies, fish.time));
  (trip.notePhotos || []).forEach(photo => add(`photo-${photo.id}`, "Photo", photo.coordinates, photo.caption || photo.filename || "Trip photo", [trip.location, photo.captureTime].filter(Boolean).join(" · "), undefined, photo.captureTime));
  (trip.liveEvents || []).forEach(event => add(`event-${event.id}`, "Live event", event.coordinates, event.title, [trip.location, event.time, event.detail].filter(Boolean).join(" · "), undefined, event.time));
  return points;
}

export function MapScreen() {
  const { logbook, activeTrip, setTripCoordinates } = useLogbook();
  const router = useRouter();
  const [species, setSpecies] = useState("All species"), [water, setWater] = useState("All waters"), [kind, setKind] = useState<(typeof kinds)[number]>("All records"), [view, setView] = useState<"Map" | "List" | "Density">("Map"), [selectedId, setSelectedId] = useState<string>(), [locationError, setLocationError] = useState("");
  const allPoints = useMemo(() => logbook.trips.flatMap(pointsForTrip), [logbook.trips]);
  const waters = useMemo(() => ["All waters", ...Array.from(new Set(allPoints.map(point => point.waterbody).filter((value): value is string => Boolean(value))))], [allPoints]);
  const speciesOptions = useMemo(() => ["All species", ...Array.from(new Set(allPoints.map(point => point.species).filter((value): value is string => Boolean(value))))], [allPoints]);
  const points = useMemo(() => allPoints.filter(point => (species === "All species" || point.species === species) && (water === "All waters" || point.waterbody === water) && (kind === "All records" || point.kind === kind)), [allPoints, species, water, kind]);
  const hotspots = useMemo(() => { const groups=new Map<string,{latitude:number;longitude:number;count:number;species:Set<string>;waters:Set<string>;tripIds:Set<string>}>(); points.filter(point=>point.kind==="Catch").forEach(point=>{const key=`${point.latitude.toFixed(3)},${point.longitude.toFixed(3)}`,group=groups.get(key)||{latitude:point.latitude,longitude:point.longitude,count:0,species:new Set(),waters:new Set(),tripIds:new Set()};group.count++;if(point.species)group.species.add(point.species);if(point.waterbody)group.waters.add(point.waterbody);group.tripIds.add(point.tripId);groups.set(key,group)});return [...groups.values()].sort((a,b)=>b.count-a.count) }, [points]);
  const selected = points.find(point => point.id === selectedId);
  const markPosition = async () => { setLocationError(""); try { await setTripCoordinates(await currentCoordinates()); } catch (error) { setLocationError(error instanceof Error ? error.message : "Could not read this position."); } };
  const clear = () => { setSpecies("All species"); setWater("All waters"); setKind("All records"); };
  return <Screen>
    <TopBar title="Map" subtitle="Every geotagged trip record, in context" actions={<View style={s.toggle}><Toggle label="Map" active={view === "Map"} onPress={() => setView("Map")} /><Toggle label="List" active={view === "List"} onPress={() => setView("List")} /><Toggle label="Density" active={view === "Density"} onPress={() => setView("Density")} /></View>} />
    {activeTrip ? <View style={s.live}><View style={s.grow}><Text style={s.liveLabel}>● LIVE POSITION</Text><Text style={s.liveTitle}>{activeTrip.location || activeTrip.title}</Text><Text style={s.muted}>{activeTrip.coordinates ? `${activeTrip.coordinates.latitude.toFixed(5)}, ${activeTrip.coordinates.longitude.toFixed(5)}` : "No trip position marked yet"}</Text></View><PrimaryButton compact label="Mark Position" onPress={markPosition} /></View> : null}
    {locationError ? <Text style={s.error}>{locationError}</Text> : null}
    <View style={s.filters}><Filter label="SPECIES" value={species} onPress={() => setSpecies(cycle(speciesOptions, species))} /><Filter label="WATERBODY" value={water} onPress={() => setWater(cycle(waters, water))} /><Filter label="RECORD TYPE" value={kind} onPress={() => setKind(cycle(kinds, kind) as (typeof kinds)[number])} />{species !== "All species" || water !== "All waters" || kind !== "All records" ? <Pressable onPress={clear}><Text style={s.clear}>Clear filters</Text></Pressable> : null}</View>
    <MetricStrip metrics={[{ label: "Mapped", value: points.length }, { label: "Catches", value: points.filter(point => point.kind === "Catch").length }, { label: "Lost", value: points.filter(point => point.kind === "Lost fish").length }, { label: "Waters", value: new Set(points.map(point => point.waterbody).filter(Boolean)).size }]} />
    {!points.length ? <EmptyState title="No mapped records" description="Add a trip position or geotag catches and photos. Native builds show interactive map tiles; the record list remains available everywhere." /> : view === "Map" ? <><View style={s.mapFrame}><MapCanvas points={points} onSelect={point => setSelectedId(point.id)} /></View>{selected ? <RecordRow point={selected} onPress={() => router.push(`/trip/${selected.tripId}`)} selected /> : <Text style={s.hint}>Tap a marker for its trip and record details.</Text>}</> : view === "List" ? <View style={s.list}>{points.map(point => <RecordRow key={point.id} point={point} onPress={() => router.push(`/trip/${point.tripId}`)} />)}</View> : hotspots.length ? <View style={s.list}>{hotspots.map((spot,index)=><View key={`${spot.latitude}-${spot.longitude}`} style={s.densityRow}><Text style={s.densityRank}>{index+1}</Text><View style={s.grow}><Text style={s.rowTitle}>{spot.count} landed at this hotspot</Text><Text style={s.muted}>{spot.latitude.toFixed(4)}, {spot.longitude.toFixed(4)} · {[...spot.waters].join(", ")||"Unknown water"}</Text><Text style={s.kind}>{[...spot.species].join(" · ")||"Species unknown"} · {spot.tripIds.size} trips</Text></View></View>)}</View> : <EmptyState title="No catch density yet" description="Density groups landed catches within roughly 100 metres. Add catch GPS points or broaden the active filters." />}
  </Screen>;
}

function Toggle({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { return <Pressable onPress={onPress} style={[s.toggleButton, active && s.toggleActive]}><Text style={[s.toggleText, active && s.toggleTextActive]}>{label}</Text></Pressable>; }
function Filter({ label, value, onPress }: { label: string; value: string; onPress: () => void }) { return <View style={s.filter}><Text style={s.label}>{label}</Text><SecondaryButton compact label={`${value}  ▾`} onPress={onPress} style={s.filterButton} /></View>; }
function RecordRow({ point, onPress, selected = false }: { point: Point; onPress: () => void; selected?: boolean }) { return <Pressable onPress={onPress} style={({ pressed }) => [s.row, selected && s.selected, pressed && s.pressed]}><View style={s.kindDot} /><View style={s.grow}><View style={s.rowTop}><Text style={s.kind}>{point.kind.toUpperCase()}</Text><Text style={s.coords}>{point.latitude.toFixed(4)}, {point.longitude.toFixed(4)}</Text></View><Text style={s.rowTitle}>{point.title}</Text><Text style={s.muted}>{point.subtitle || point.waterbody || "Mapped record"}</Text></View><Text style={s.chevron}>›</Text></Pressable>; }

const s = StyleSheet.create({
  toggle:{flexDirection:"row",borderWidth:1,borderColor:tokens.color.line,borderRadius:8,overflow:"hidden"},toggleButton:{paddingHorizontal:9,paddingVertical:7,backgroundColor:tokens.color.panelSoft},toggleActive:{backgroundColor:tokens.color.activeBackground},toggleText:{color:tokens.color.muted,fontSize:11,fontWeight:"800"},toggleTextActive:{color:tokens.color.greenDark},live:{flexDirection:"row",alignItems:"center",gap:12,padding:14,borderWidth:1,borderColor:tokens.color.green,borderRadius:9,backgroundColor:tokens.color.activeBackground},grow:{flex:1},liveLabel:{color:tokens.color.green,fontSize:10,fontWeight:"900",letterSpacing:.5},liveTitle:{color:tokens.color.text,fontSize:16,fontWeight:"800",marginVertical:3},muted:{color:tokens.color.muted,fontSize:12,lineHeight:17},error:{color:tokens.color.red,fontSize:13},filters:{flexDirection:"row",alignItems:"flex-end",flexWrap:"wrap",gap:10,padding:12,borderWidth:1,borderColor:tokens.color.line,borderRadius:9,backgroundColor:tokens.color.panel},filter:{flexGrow:1,minWidth:105,gap:5},label:{color:tokens.color.muted,fontSize:10,fontWeight:"900",letterSpacing:.5},filterButton:{alignItems:"flex-start"},clear:{color:tokens.color.greenDark,fontSize:12,fontWeight:"800",paddingVertical:10},mapFrame:{overflow:"hidden",borderWidth:1,borderColor:tokens.color.line,borderRadius:10},hint:{color:tokens.color.muted,textAlign:"center",fontSize:12},list:{borderWidth:1,borderColor:tokens.color.line,borderRadius:9,overflow:"hidden"},row:{minHeight:82,flexDirection:"row",alignItems:"center",gap:11,padding:13,backgroundColor:tokens.color.panel,borderBottomWidth:1,borderBottomColor:tokens.color.line},selected:{borderWidth:1,borderColor:tokens.color.green,backgroundColor:tokens.color.activeBackground,borderRadius:9},pressed:{backgroundColor:tokens.color.hover},kindDot:{width:9,height:9,borderRadius:5,backgroundColor:tokens.color.green},rowTop:{flexDirection:"row",justifyContent:"space-between",gap:8},kind:{color:tokens.color.greenDark,fontSize:10,fontWeight:"900",letterSpacing:.4},coords:{color:tokens.color.muted,fontSize:10},rowTitle:{color:tokens.color.text,fontSize:15,fontWeight:"800",marginVertical:3},chevron:{color:tokens.color.muted,fontSize:24},densityRow:{minHeight:82,flexDirection:"row",alignItems:"center",gap:11,padding:13,backgroundColor:tokens.color.panel,borderBottomWidth:1,borderBottomColor:tokens.color.line},densityRank:{width:30,color:tokens.color.green,fontSize:22,fontWeight:"900"},
});
